### PR TITLE
config: fix sslmode typo in reference.yml

### LINKED ISSUE #9142: PostgreSQL sslmode in reference file wrong
### Describe the bug

PostgreSQL SSL mode "require**d**" invalid. Should be "require". See [postgresql doc](https://www.postgresql.org/docs/9.1/libpq-ssl.html)

### To Reproduce

1. Use the reference config which [contains sslmode: required](https://github.com/oss-review-toolkit/ort/blob/0b24c91542e0598e83e7d359914a47d1a82df338/model/src/main/resources/reference.yml#L196)
2. Then run the scan

### Expected behavior

Information is cached in PostgreSQL database. Database can be accessed.

### Console / log output

`PoolInitializationException: Failed to initialize pool: Invalid sslmode value: required`

### Environment

```
 ______________________________                                                
/        \_______   \__    ___/  The OSS Review Toolkit, version 31.0.0,       
|    |   | |       _/ |    |     built with JDK 11.0.24+8, running under Java 2
|    |   | |    |   \ |    |     Executing 'requirements' as 'AzDevOps' on Linu
\________/ |____|___/ |____|     with 4 CPUs and a maximum of 3996 MiB of memor
```

```
    fileListStorage:
      postgresStorage:
        connection:
          url: "jdbc:postgresql://%POSTGRESQL_URL%/%POSTGRESQL_DB%"
          schema: "public"
          username: "%POSTGRESQL_USER%"
          password: "%POSTGRESQL_PW%"
          sslmode: required
```

### PR DESCRIPTION
**Pull request by georg-eckert-zeiss**
This PR fixes #9142 by using the correct sslmodes in the reference file. A checked the kotlin file representing the config, too. There it is spelled correctly.

### CODE REVIEW

**Comment by sschuberth** [comment]
Thanks for the fix. Please also add a link to a reference to the commit message, like https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-SSLMODE-STATEMENTS. Syntax-wise you should do this via a footnote, like

```
See [1] for the list of valid `sslmode` values.

[1]: https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-SSLMODE-STATEMENTS
```

**Comment by sschuberth** [comment]
Please see the failing commit-lint check; you need to follow conventional commits syntax and amend your existing commit accordingly.

**Comment by georg-eckert-zeiss** [comment]
> Thanks for the fix. Please also add a link to a reference to the commit message, like https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-SSLMODE-STATEMENTS. Syntax-wise you should do this via a footnote, like
> 
> ```
> See [1] for the list of valid `sslmode` values.
> 
> [1]: https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-SSLMODE-STATEMENTS
> ```

done

**Comment by sschuberth** [comment]
We don't allow merge commits as part of PRs. Please instead rebase / edit existing commit to fixup things discovered during the review.

**Comment by georg-eckert-zeiss** [comment]
> We don't allow merge commits as part of PRs. Please instead rebase / edit existing commit to fixup things discovered during the review.

ok. github suggested it with a button to click :D - done

**Review by fviernau — APPROVED** [review]

**Comment by georg-eckert-zeiss** [comment]
> @georg-eckert-zeiss You may need to updated `OrtConfigurationTest.kt`.

done

**Review by sschuberth — APPROVED** [review]

**Pull request merged**
