### PR TITLE
Dockerfile: Switch building to a base image with Java 11

### LINKED ISSUE #3318: [Docker] Failed to build
Hi, 

I updated my ort source this morning, and now the build docker is failing.
There is a compilation error :
```
#14 34.57 > Task :downloader:compileKotlin FAILED
#14 34.57 e: /usr/local/src/ort/downloader/src/main/kotlin/vcs/Subversion.kt: (268, 46): Unresolved reference: requestPasswordAuthenticationInstance
#14 34.57
#14 34.57 FAILURE: Build failed with an exception.
```
The method requestPasswordAuthenticationInstance  is not in jdk8 but in the 9.
```
    /**
     * Ask this authenticator for a password.
     *
     * @param host The hostname of the site requesting authentication.
     * @param addr The InetAddress of the site requesting authorization,
     *             or null if not known.
     * @param port the port for the requested connection
     * @param protocol The protocol that's requesting the connection
     *          ({@link java.net.Authenticator#getRequestingProtocol()})
     * @param prompt A prompt string for the user
     * @param scheme The authentication scheme
     * @param url The requesting URL that caused the authentication
     * @param reqType The type (server or proxy) of the entity requesting
     *              authentication.
     *
     * @return The username/password, or null if one can't be gotten
     *
     * @since 9
     */
    public PasswordAuthentication
    requestPasswordAuthenticationInstance(String host,
                                          InetAddress addr,
                                          int port,
                                          String protocol,
                                          String prompt,
                                          String scheme,
                                          URL url,
                                          RequestorType reqType)
```
We have to change `FROM frolvlad/alpine-java:jdk8-slim AS build` to go to a jdk9.
But which one to choose?

### PR DESCRIPTION
**Pull request by sschuberth**
Fixes #3318.

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

### CODE REVIEW

**Review by oheger-bosch — COMMENTED** [review]
The change looks good from my perspective and should be safe, especially as we already build and run ORT with Java 11.

However, as I haven't used the Docker image so far, I am probably not qualified to approve this.

**Comment by MarcelBochtler** [comment]
I'm able to build the image and as it is already using `adoptopenjdk:11-jre-hotspot-bionic` as runtime I don't see any issues with using jdk 11 for the build container.

**Comment by sschuberth** [comment]
> Also my analyzer and scanner smoketests were successful.

So, do you dare to approve? 😀

**Comment by sschuberth** [comment]
Also, AFAIK HERE Technologies is not using the official Dockerfile at all, so we should be safe merging this.

**Review by MarcelBochtler — APPROVED** [review]

**Pull request merged**
