### PR TITLE
Severity: Swap ordering of enum members

### PR DESCRIPTION
**Pull request by sschuberth**
This way a more natural comparison like "severity > Severity.HINT" can
be done.

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

### CODE REVIEW

**Review by nnobelis — DISMISSED** [review]

**Comment by nnobelis** [comment]
when this is merged, I will adapt https://github.com/oss-review-toolkit/ort/pull/3955

**Review by oheger-bosch — COMMENTED** [review]
While I do not object this change, I find the approach to rely on the order of enum constants a bit brittle - especially as everything else in the codebase is alphabetically ordered. I had a look into Bloch's "Effective Java", 3rd edition: There are the items 35 "Use instance fields instead of ordinals" and 37 "Use EnumMap instead of ordinal indexing" related to the topic; but both talk about the `ordinal()` function and not directly about the order of enum constants.

A more explicit approach could be to have the `Severity` class provide methods to compare constants or a `Comparator`.

**Comment by sschuberth** [comment]
> I find the approach to rely on the order of enum constants a bit brittle

I agree it's a bit brittle, but that's why I decided to at least add a code comment here.

> especially as everything else in the codebase is alphabetically ordered.

Note, however, that *this* enum wasn't alphabetically sorted before. Also other enums like `HashAlgorithm` are not. In general, we tend to not sort enum members alphabetically, but by meaning.

**Comment by mnonnenmacher** [comment]
I'm a bit undecided about this, I don't really like relying on the order of the enum, but on the other hand you cannot override `compareTo` for enums, so any other solution would require a separate function or comparator which would be less elegant to use. We have the dev meeting in an hour, we could discuss this there?

**Comment by sschuberth** [comment]
> We have the dev meeting in an hour, we could discuss this there?

I've put it onto the agenda.

**Review by mnonnenmacher — APPROVED** [review]

**Review by fviernau — APPROVED** [review]

**Pull request merged**
