### PR TITLE
Create database connections lazily

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

### CODE REVIEW

**Comment by mnonnenmacher** [comment]
Creating the connection early has the benefit that it fails immediately if the configuration is wrong. You would not want to find out that the archiver configuration is wrong only after a potentially very long lasting scan.

**Comment by sschuberth** [comment]
> Creating the connection early has the benefit that it fails immediately if the configuration is wrong. You would not want to find out that the archiver configuration is wrong only after a potentially very long lasting scan.

FYI, the reason I was doing this change is to make the workbench work for me: Right now, the workbench creates the `OrtApi` incl. a `fileArchiver` right at the start when loading a file. This means I cannot even load a file if the archiver configuration is wrong.

Do you have a better proposal how to solve this? Maybe we could simply add come `testConnection()` function that could be used to explicitly test the connection when wanted?

**Comment by mnonnenmacher** [comment]
> FYI, the reason I was doing this change is to make the workbench work for me: Right now, the workbench creates the `OrtApi` incl. a `fileArchiver` right at the start when loading a file. This means I cannot even load a file if the archiver configuration is wrong.
>
> Do you have a better proposal how to solve this? Maybe we could simply add come `testConnection()` function that could be used to explicitly test the connection when wanted?

To me it's two things that should be done, first the workbench should handle such errors better and probably allow to ignore them or disable certain parts of the configuration, and second the data sources should be initialized lazily as you propose with an optional function to test the configuration which the ORT CLI should call on start.

However, what I don't like about the current implementation is that it makes the Hikari config a dependency of the archiver class. I don't have a better idea right know, but let's discuss this offline tomorrow.

**Comment by sschuberth** [comment]
> However, what I don't like about the current implementation is that it makes the Hikari config a dependency of the archiver class. I don't have a better idea right know, but let's discuss this offline tomorrow.

I've found a different solution, please see https://github.com/oss-review-toolkit/ort/pull/5091. Closing in favor of that one.

**Pull request closed without merging**
