### PR TITLE
analyzer: Add a generic OrtDefinitionFile "fake" package manager

### PR DESCRIPTION
**Pull request by sschuberth**
Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

### CODE REVIEW

**Comment by tsteenbe** [comment]
@sschuberth  We actually planning to add a SPDX package manager to ORT based on `package.spdx.yml` described in  https://github.com/spdx/spdx-spec/issues/439 to capture dependencies for C/C++ projects that are committed to the repo.

**Comment by sschuberth** [comment]
That basically sounds nice @tsteenbe, but what's the time frame for this? Sounds like proposal first should be spec'ed out by SPDX before using it widely.

Also, in your [example](https://github.com/spdx/spdx-spec/issues/439#issue-643990957), where's the directory name referenced? Is it the `name` field?

**Comment by tsteenbe** [comment]
It does not need to be spec'ed as everything we need is already part of SPDX 2.2 - the only new thing we would introduce is to name the file by default `package.spdx.yml` but we could also say in ort that the SPDX package manager looks for all files ending with `.spdx.yml` or `.spdx.yml`.

Directory goes in the `PackageFileName` field see [3.4.5 example](https://github.com/spdx/spdx-spec/blob/master/chapters/3-package-information.md#34-package-file-name-)

So if `curl 7.70.0` is included in `./myrootdir/myproject/libs/curl` the example would be:
```
SPDXID: "SPDXRef-DOCUMENT"
spdxVersion: "SPDX-2.2"
creationInfo:
  created: "2020-07-23T18:30:22Z"
  creators:
  - "Organization: The SPDX project"
  - "Person: Thomas Steenbergen"
  licenseListVersion: "3.9"
name: "curl-7.70.0"
dataLicense: "CC0-1.0"
documentNamespace: "http://spdx.org/spdxdocs/spdx-document-curl"
documentDescribes:
- "SPDXRef-Package-curl"
packages:
- SPDXID: "SPDXRef-Package-curl"
  comment: "A command line tool and library for transferring data with URL syntax, supporting \
     HTTP, HTTPS, FTP, FTPS, GOPHER, TFTP, SCP, SFTP, SMB, TELNET, DICT, LDAP, LDAPS, MQTT, FILE, \
     IMAP, SMTP, POP3, RTSP and RTMP. libcurl offers a myriad of powerful features."
  copyrightText: "Copyright (c) 1996 - 2020, Daniel Stenberg, <daniel@haxx.se>, and many
    contributors, see the THANKS file."
  downloadLocation: "https://github.com/curl/curl/releases/download/curl-7_70_0/curl-7.70.0.tar.gz"
  filesAnalyzed: false
  homepage: "https://curl.haxx.se/"
  licenseConcluded: "NOASSERTION"
  licenseDeclared: "curl"
  name: "curl"
  PackageFileName: "./myrootdir/myproject/libs/curl"
  versionInfo: "7.70.0"
```

**Comment by sschuberth** [comment]
> name the file by default `package.spdx.yml` but we could also say in ort that the SPDX package manager looks for all files ending with `.spdx.yml` or `.spdx.yml`.

I like the latter approach, so you could even name the file after the package name, or use `packages.spdx.yml` (plural).

> you place the `package.spdx.yml` in the root of directory containing the OSS lib

That wouldn't work for our use-case. We have a directory structure like

```
project / repo root
|
+-external
  |
  + libA
  |
  + libB
  |
  .
  .
```

where `libA` and `libB` are Git submodules, and we cannot put `*.spdx.yml` directly into any of these. What we preferably would like to do is to put a *single* file into either the project / repo root or the "external" sub-directory that describes *all* dependencies in `libA`, `libB` etc.

Would that be possible with the a single `package(s).spdx.yml` file? What would I put into the *top-level* `name:` field (the one after `creationInfo:`) in that case?

**Comment by tsteenbe** [comment]
> Would that be possible with the a single `package(s).spdx.yml` file? What would I put into the _top-level_ `name:` field (the one after `creationInfo:`) in that case?

In your scenario the top level `name` is always the name of project so in your scenario it would be the name of the project / repo root.

By the way it singular `package.spdx.yml` as even if it holds multiple packages - think of it as a root package that hold other packages.

**Comment by sschuberth** [comment]
Closing this in favor of an upcoming PR that will use the SPDX file.

**Comment by sschuberth** [comment]
> By the way it singular `package.spdx.yml` as even if it holds multiple packages - think of it as a root package that hold other packages.

This is still confusing IMO, and then the file should probably be called `project.spdx.yml` instead, for the same reason we distinguish between "project" and "package" in ORT.

**Comment by tsteenbe** [comment]
The concept of a `project` is not something that exist in SPDX.

@sschuberth  What do you think if we update the proposal in https://github.com/spdx/spdx-spec/issues/439 to the following:

The package manifest file must end with extension `.spdx.yml`, `.spdx.yaml` or `.spdx.json`. 

We recommend to use:
- `package` for the name of the file e.g. `package.spdx.yml` if you are describing a single package, or
- `project` for the name of the file e.g.  `project.spdx.yml` or `[name of project].spdx.yml` if you describing a project that holds multiple other packages.

**Comment by sschuberth** [comment]
> if you are describing a single package

I just think we should probably be clearer here, and say that the "root" package in this case is the same as the single package under "packages:".

**Comment by sschuberth** [comment]
> Closing this in favor of an upcoming PR that will use the SPDX file.

See https://github.com/oss-review-toolkit/ort/pull/2838.

**Pull request closed without merging**
