### PR TITLE
Make use of GRADLE_OPTS

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

### CODE REVIEW

**Comment by sschuberth** [comment]
Hmm, we [still getting](https://dev.azure.com/oss-review-toolkit/ort/_build/results?buildId=4927&view=logs&j=0b98c9ad-b4dd-509f-97af-ff0d5e511683&t=d4a109d9-63b6-59b7-7349-067146a0a444&l=81) "Unable to watch the file system for changes. The inotify watches limit is too low." despite ``.

**Comment by mnonnenmacher** [comment]
> Hmm, we [still getting](https://dev.azure.com/oss-review-toolkit/ort/_build/results?buildId=4927&view=logs&j=0b98c9ad-b4dd-509f-97af-ff0d5e511683&t=d4a109d9-63b6-59b7-7349-067146a0a444&l=81) "Unable to watch the file system for changes. The inotify watches limit is too low." despite `-Dorg.gradle.vfs.watch=false`.

It looks like `GRADLE_OPTS` is not working as expected because it also prints this line at the beginning:
```
Starting a Gradle Daemon (subsequent builds will be faster)
```

**Comment by mnonnenmacher** [comment]
Maybe you have to set the `gradleOpts` option of the Gradle tasks like this:
```
gradleOptions: ${{ variables.GRADLE_OPTS }}
```
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gradle?view=azure-devops#arguments

**Comment by sschuberth** [comment]
> Maybe you have to set the `gradleOpts` option of the Gradle tasks like this:

Hmm, thanks for the hint, but I'm but sure if it's even worth a try, as that would defeat the purpose to not touch every Gradle task call to pass common options.

**Comment by sschuberth** [comment]
> It looks like `GRADLE_OPTS` is not working as expected because it also prints this line at the beginning:
> 
> ```
> Starting a Gradle Daemon (subsequent builds will be faster)
> ```

I also find the Gradle docs in that regard confusing. Some sources claim that even with `--no-daemon` the daemon *is* actually started, but shut down again immediately after the build. Other sources indicate that really no daemon is started...

**Comment by mnonnenmacher** [comment]
> > Maybe you have to set the `gradleOpts` option of the Gradle tasks like this:
> 
> Hmm, thanks for the hint, but I'm but sure if it's even worth a try, as that would defeat the purpose to not touch every Gradle task call to pass common options.

Maybe it could be set in `.azure-pipelines.yml`, then there would at least only one central place to define those options.

**Comment by sschuberth** [comment]
This is obsolete now that CI tests are not run in Azure Pipelines anymore as of https://github.com/oss-review-toolkit/ort/pull/5031.

**Pull request closed without merging**
