### PR TITLE
PostgresStorage: Use the Exposed API to check if the table exists

### PR DESCRIPTION
**Pull request by mnonnenmacher**
Use a function from the Exposed API to check if the table exists,
because this requires less code than the custom query.

### CODE REVIEW

**Review by oheger-bosch — COMMENTED** [review]
I ran some tests with out setup, but it looks like as an already existing table is not detected:

When using a fresh and empty schema, the *scan_results* table is correctly created. When using a schema which contains the table, I get the following output:

```
08:31:45.416 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
08:31:47.338 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
08:31:48.619 [main] INFO  Exposed - Preparing create tables statements took 31ms
08:31:48.635 [main] INFO  Exposed - Executing create tables statements took 16ms
08:31:48.713 [main] INFO  Exposed - Extracting table columns took 78ms
08:31:48.776 [main] INFO  Exposed - Extracting column constraints took 63ms
08:31:48.776 [main] INFO  Exposed - Preparing alter table statements took 141ms
08:31:48.791 [main] INFO  Exposed - Executing alter table statements took 15ms
08:31:48.854 [main] INFO  Exposed - Checking mapping consistence took 63ms
08:31:48.916 [main] WARN  Exposed - Transaction attempt #0 failed: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block. Statement(s): DELETE FROM busy
org.jetbrains.exposed.exceptions.ExposedSQLException: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:63) ~[exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:129) ~[exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:115) ~[exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:29) ~[exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.statements.DeleteStatement$Companion.all(DeleteStatement.kt:24) ~[exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.QueriesKt.deleteAll(Queries.kt:63) ~[exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.SchemaUtils.withDataBaseLock(SchemaUtils.kt:274) ~[exposed-core-0.29.1.jar:?]
        at org.ossreviewtoolkit.scanner.storages.PostgresStorage$setupDatabase$2.invoke(PostgresStorage.kt:93) ~[scanner.jar:?]
        at org.ossreviewtoolkit.scanner.storages.PostgresStorage$setupDatabase$2.invoke(PostgresStorage.kt:92) ~[scanner.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:170) [exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:191) [exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:199) [exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:190) [exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:148) [exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:199) [exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:120) [exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:118) [exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:117) [exposed-core-0.29.1.jar:?]
        at org.ossreviewtoolkit.scanner.storages.PostgresStorage.setupDatabase(PostgresStorage.kt:92) [scanner.jar:?]
        at org.ossreviewtoolkit.scanner.storages.PostgresStorage.<init>(PostgresStorage.kt:81) [scanner.jar:?]
        at org.ossreviewtoolkit.scanner.ScanResultsStorage$Companion.createPostgresStorage(ScanResultsStorage.kt:179) [scanner.jar:?]
        at org.ossreviewtoolkit.scanner.ScanResultsStorage$Companion.createStorage(ScanResultsStorage.kt:118) [scanner.jar:?]
        at org.ossreviewtoolkit.scanner.ScanResultsStorage$Companion.configure(ScanResultsStorage.kt:78) [scanner.jar:?]
        at org.ossreviewtoolkit.commands.ScannerCommand.configureScanner(ScannerCommand.kt:126) [cli.jar:?]
        at org.ossreviewtoolkit.commands.ScannerCommand.run(ScannerCommand.kt:171) [cli.jar:?]
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:180) [clikt-jvm-3.1.0.jar:?]
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:189) [clikt-jvm-3.1.0.jar:?]
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:17) [clikt-jvm-3.1.0.jar:?]
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:396) [clikt-jvm-3.1.0.jar:?]
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:393) [clikt-jvm-3.1.0.jar:?]
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:411) [clikt-jvm-3.1.0.jar:?]
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:436) [clikt-jvm-3.1.0.jar:?]
        at org.ossreviewtoolkit.OrtMainKt.main(OrtMain.kt:220) [cli.jar:?]
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553) ~[postgresql-42.2.19.jar:42.2.19]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285) ~[postgresql-42.2.19.jar:42.2.19]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323) ~[postgresql-42.2.19.jar:42.2.19]
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481) ~[postgresql-42.2.19.jar:42.2.19]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401) ~[postgresql-42.2.19.jar:42.2.19]
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164) ~[postgresql-42.2.19.jar:42.2.19]
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130) ~[postgresql-42.2.19.jar:42.2.19]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-4.0.3.jar:?]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-4.0.3.jar:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeUpdate(JdbcPreparedStatementImpl.kt:23) ~[exposed-jdbc-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.statements.DeleteStatement.executeInternal(DeleteStatement.kt:9) ~[exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.statements.DeleteStatement.executeInternal(DeleteStatement.kt:6) ~[exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:61) ~[exposed-core-0.29.1.jar:?]
        ... 32 more
Caused by: org.postgresql.util.PSQLException: ERROR: relation "identifier_and_scanner_version" already exists
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553) ~[postgresql-42.2.19.jar:42.2.19]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285) ~[postgresql-42.2.19.jar:42.2.19]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323) ~[postgresql-42.2.19.jar:42.2.19]
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481) ~[postgresql-42.2.19.jar:42.2.19]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401) ~[postgresql-42.2.19.jar:42.2.19]
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164) ~[postgresql-42.2.19.jar:42.2.19]
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130) ~[postgresql-42.2.19.jar:42.2.19]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-4.0.3.jar:?]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-4.0.3.jar:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeUpdate(JdbcPreparedStatementImpl.kt:23) ~[exposed-jdbc-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:96) ~[exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:61) ~[exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:129) ~[exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:115) ~[exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:91) ~[exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:82) ~[exposed-core-0.29.1.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec$default(Transaction.kt:82) ~[exposed-core-0.29.1.jar:?]
        at org.ossreviewtoolkit.scanner.storages.PostgresStorage.createIdentifierAndScannerVersionIndex(PostgresStorage.kt:122) ~[scanner.jar:?]
        at org.ossreviewtoolkit.scanner.storages.PostgresStorage.access$createIdentifierAndScannerVersionIndex(PostgresStorage.kt:63) ~[scanner.jar:?]
        at org.ossreviewtoolkit.scanner.storages.PostgresStorage$setupDatabase$2$1.invoke(PostgresStorage.kt:101) ~[scanner.jar:?]
        at org.ossreviewtoolkit.scanner.storages.PostgresStorage$setupDatabase$2$1.invoke(PostgresStorage.kt:93) ~[scanner.jar:?]
        at org.jetbrains.exposed.sql.SchemaUtils.withDataBaseLock(SchemaUtils.kt:272) ~[exposed-core-0.29.1.jar:?]
        ... 26 more
08:31:49.088 [main] INFO  org.ossreviewtoolkit.scanner.ScanResultsStorage - ScanResultStorage has been configured to PostgresStorage.

```
The scan then continues, and cached results can be loaded successfully.

**Review by fviernau — DISMISSED** [review]

**Comment by sschuberth** [comment]
@fviernau I believe we should investigate the issue Oliver reported before merging this.

**Comment by mnonnenmacher** [comment]
> I ran some tests with out setup, but it looks like as an already existing table is not detected:

Thanks for checking, I missed that the table names contain the schema name which is fixed now.

**Comment by oheger-bosch** [comment]
> Thanks for checking, I missed that the table names contain the schema name which is fixed now.

Yes, I can confirm that an already existing table is now correctly detected.

**Review by oheger-bosch — APPROVED** [review]
Tested successfully with our setup.

**Pull request merged**
