### PR TITLE
Dockerfile: Upgrade Scancode to version 3.2.1rc2

### PR DESCRIPTION
**Pull request by fb33**

### CODE REVIEW

**Review by fviernau — APPROVED** [review]
^^ I was just about to do that, you were faster...thanks!

**Comment by fviernau** [comment]
> I'd like to give this some testing before get merged.

Is it covered by any automated checks actually?

**Comment by sschuberth** [comment]
> Is it covered by any automated checks actually?

Just the building of the `Dockerfile`, yes, but I'd like to test other things, like which Python version is now used by ScanCode during its configuration.

**Comment by sschuberth** [comment]
ScanCode still uses Python 2 this way, but I'll fix it later so that Python 3 is used.

**Pull request merged**
