### PR TITLE
feat(cli): Add the flag `--monitor-stack-traces`

### PR DESCRIPTION
**Pull request by fviernau**
If `ort` executes slowly this can become handy for getting a first hint where the CPU work is happening.

Note: Print the stack traces in reverse order and the `main` thread's trace at the bottom to have the likely desired information at the most prominent place.

### CODE REVIEW

**Comment by sschuberth** [comment]
Hmm, I'm unsure whether this is a feature that we should add. It sounds more like something that should be done during debugging with the means of an IDE. Or are there really cases you'd like to inspect e.g. on CI that absolutely cannot be reproduced locally?

Also, this reminds me a bit of https://github.com/oss-review-toolkit/ort/issues/3296. IMO a much nicer (but also more involving) solution for monitoring would be to print better progress information on the CLI, similar to like Gradle does when building with multiple threads in parallel.

**Comment by fviernau** [comment]
> Hmm, I'm unsure whether this is a feature that we should add. It sounds more like something that should be done during debugging with the means of an IDE. 

Can you explain which exact means you are referring to, and why these means should be preferable.
(If you're talking about a profiler, then I'd say the use cases are related but both approaches has pros and cons. If I used
the profiler for profiling my evaluator run, I would have waited ages for it to finish due to the large ORT file size. I'm not saying the profiler is not suitable, but looking at the thread dumps certainly gave me some insight more quickly.) 

> Or are there really cases you'd like to inspect e.g. on CI that absolutely cannot be reproduced locally?

It's not for CI, it's for local investigations. It could also be local on some other devs machine, so remote to myself.

> Also, this reminds me a bit of #3296. IMO a much nicer (but also more involving) solution for monitoring would be to print better progress information on the CLI, similar to like Gradle does when building with multiple threads in parallel.

In my use case the CLI output of ORT just didn't print anything, so I wanted to get a hunch on what it's doing.
If one could anticipate all performance problems and put logging making it visible everywhere, then the performance problem wouldn''t exist in the first place.

I've written this code already a couple of times and I wanted to save that effort for myself and others as well.
So, do you think seeing stack traces cannot be useful for any developer using ORT ?

**Comment by sschuberth** [comment]
> Can you explain which exact means you are referring to

I wasn't thinking about using a profiler, but the threads view of the debugger tab in the IDE. You can pause execution of threads and look at the stacktrace at any time.

> and why these means should be preferable.

Since it's you who wants to introduce this change, could you please explain why your approach should be preferred over dedicated debugging tools?

> In my use case the CLI output of ORT just didn't print anything

Yes, that's exactly what #3296 is about: Missing information about progress. This should not necessarily be implemented by simply adding more log statement, but ideally by implementing progress interfaces. But that's, as mentioned, a bigger effort.

> If one could anticipate all performance problems and put logging making it visible everywhere, then the performance problem wouldn''t exist in the first place.

I don't get that sentence. How does more logging automatically solve performance problems?

> So, do you think seeing stack traces cannot be useful for any developer using ORT ?

Obviously, I cannot tell for the rest of @oss-review-toolkit/kotlin-devs, but I myself have never needed it / more than what the IDE debugging offers.

> Would it work for you if this feature was toggled via env var instead via a CI param, or is the feature itself not convincing?

To me, the feature itself is not convincing, as it seems to reimplement something that is already available in the IDE, or via some of the tools e.g. mentioned [here](https://www.baeldung.com/java-thread-dump).

**Comment by fviernau** [comment]
`jstack` can be used for this purpose, e.g.

**Pull request closed without merging**
