### PR TITLE
Analyzer: Remove projects that are also dependencies

### PR DESCRIPTION
**Pull request by bennati**
Local directories that are dependencies can appear in the
analyzer results both as packages, e.g. Pub, and projects.
After building the results, projects are removed if they match
with packages on VCS information and package manager type.

This is caused by issue #5365. This is only a workaround which
should be replaced by a comprehensive solution for #5365.

Please ensure that your pull request adheres to our [contribution guidelines](https://github.com/oss-review-toolkit/.github/blob/main/CONTRIBUTING.md). Thank you!

### CODE REVIEW

**Comment by bennati** [comment]
We have a project where ~20 packages are mistakenly identified as projects, I'm not even sure how to solve these issues using curations.
A proper fix is likely too far away for our release schedule.
Happy to evaluate alternatives.

**Comment by mnonnenmacher** [comment]
@sschuberth What do you mean by per-package-manager? This seems to be a generic workaround that affects all package managers where the described issue could appear.

@bennati I would rather know more details about the issue and fix the root cause instead of adding this workaround. Can you provide more details in which case projects also appear as packages? This should not happen in general. I also don't understand how this realtes to #5365, as this PR is about project/package duplicates while the issue addresses the association of files to projects.

**Comment by bennati** [comment]
@mnonnenmacher sure, let's take an example directory structure like the following:
```
project_root/
|--- lib_dependency/
|--- app/
       |--- pubspec.yaml
```

And `pubspec.yaml` contains the following
```
dependencies:
  here_lib_dependency:
    path: ../lib_dependency
```

The scanner will first identify `lib_dependency` as a Project when traversing the file system, then the same will be identified as Package when analyzing `pubspec.yaml`. The VCS info will be the same, but the name will differ, and this raises issues as the folder is in one case identified as HERE proprietary and in the other not.

Hope this helps

**Comment by bennati** [comment]
https://github.com/oss-review-toolkit/ort/commit/cea7f66ea43c4ca61cebbed2835d5681acd8d03a 
breaks this patch.
I would like clarity on whether this contribution is actually wanted before spending time to adapt it.

**Comment by mnonnenmacher** [comment]
> [cea7f66](https://github.com/oss-review-toolkit/ort/commit/cea7f66ea43c4ca61cebbed2835d5681acd8d03a) breaks this patch. I would like clarity on whether this contribution is actually wanted before spending time to adapt it.

@bennati If anything is removed it should be the duplicate packages, not projects. Because if a `pubspec.yaml` is in the file tree it is a project from the ORT perspective.
But as mentioned above I would prefer to fix the root cause instead of adding a work-around. As the problem seems to be that the Pub implementation does not recognize that the dependency is also a local project, the real fix should solve this somehow. I won't have time to look into this anytime soon, but if you want to work on this, my suggestion would be to add a similar project dependency to our synthetic pub test project first to document the issue, and then find a way to detect project dependencies in the Pub implementation.
The solution could use a similar approach as the Maven implementation, where all projects are detected in the `beforeResolution()` function to later resolve project dependencies without having to build the Maven project.

**Comment by bennati** [comment]
@mnonnenmacher that sounds a good approach.
Given that I won't have time to work on this anytime soon either, could we go for this approach and then revert it once the full fix is implemented?

**Comment by mnonnenmacher** [comment]
> @mnonnenmacher that sounds a good approach. Given that I won't have time to work on this anytime soon either, could we go for this approach and then revert it once the full fix is implemented?

If we implement a workaround it should remove the duplicate packages, not projects. Note that a similar change was just done in #5509 for `SpdxDocumentFile`.

**Comment by mnonnenmacher** [comment]
> @mnonnenmacher that sounds a good approach. Given that I won't have time to work on this anytime soon either, could we go for this approach and then revert it once the full fix is implemented?

If we implement a workaround it should remove the duplicate packages, not projects. Note that a similar change was just done in #5509 for `SpdxDocumentFile`.

**Comment by bennati** [comment]
The reason why I removed duplicate projects instead of duplicate packages is that the correct name for the dependency is specified in `pubspec.yaml`, while the name of the corresponding project is given by the path it's in.

**Comment by mnonnenmacher** [comment]
@bennati I'm not sure what you mean by "the project was generated from the directory structure", but if you mean that the project name is the name of the folder of the definition file, that means that the fallback in this line is used:
https://github.com/oss-review-toolkit/ort/blob/1ca71eb3c2ab8b8379eb9f387b13d0b66e276b83/analyzer/src/main/kotlin/managers/Pub.kt#L445

If this is the case, it seems that the name is not properly set in the pubspec.yaml, or that the linked code needs to be improved.

**Comment by mnonnenmacher** [comment]
> If this is the case, it seems that the name is not properly set in the pubspec.yaml, or that the linked code needs to be improved.

The code was indeed wrong which means that project names were never parsed correctly, I have added a fix to #5524.

**Comment by sschuberth** [comment]
> The code was indeed wrong which means that project names were never parsed correctly, I have added a fix to #5524.

@bennati is this PR still needed with the above-mentioned PR?

**Comment by bennati** [comment]
No, we can close this

**Pull request closed without merging**
