### PR TITLE
reporter-web-app: Fix for 'cannot find '@babel/helper-call-delegate' error

### PR DESCRIPTION
**Pull request by tsteenbe**
Building task :reporter-web-app:yarnBuild fails with a
"Cannot find module '@babel/helper-call-delegate'" as
the version specified in the `yarn.lock` has been removed
from npmjs.com.

Signed-off-by: Thomas Steenbergen <thomas.steenbergen@here.com>

### CODE REVIEW

**Comment by sschuberth** [comment]
Hmm, why can't I find `@babel/helper-call-delegate` in the diff of removed lines from the lock file then?

**Comment by tsteenbe** [comment]
> Hmm, why can't I find `@babel/helper-call-delegate` in the diff of removed lines from the lock file then?

I am building the `yarn.lock` on my Mac and `@babel/helper-call-delegate` seems to be only installed on Linux that why it does not show up in the diff.

**Comment by fviernau** [comment]
I was able to reproduce the issue under Ubuntu 19.10 and verified that it is fixed by this PR via:
```
git checkout hotfix-yarn-lock
rm -rf reporter-web-app/node_modules
./gradlew installDist
```

**Comment by sschuberth** [comment]
> I am building the `yarn.lock` on my Mac and `@babel/helper-call-delegate` seems to be only installed on Linux that why it does not show up in the diff.

That's very interesting, as in the end it means that potentially more / other dependencies than those listed in a lock file get installed, which in turn means just parsing the lock file would not necessarily give us all dependencies (for all platforms).

**Pull request merged**
