### PR TITLE
Npm: Add an option to enable legacy peer dependencies

### PR DESCRIPTION
**Pull request by mnonnenmacher**
Since NPM 7 conflicts in peer dependencies lead to an error during `npm
install`, unless the `--legacy-peer-deps` flag is provided [1][2].

Add an option to `Npm` to enable this flag on demand, so that NPM 6
projects with peer dependency conflicts can be analyzed.

[1]: https://docs.npmjs.com/cli/v8/commands/npm-install#strict-peer-deps
[2]: https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major

### CODE REVIEW

**Comment by sschuberth** [comment]
> Since NPM 7 conflicts in peer dependencies lead to an error during `npm install`, unless the `--legacy-peer-deps` flag is provided [1](https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major).

I find this sentence hard to understand as it seems to continue the commit message title and is not a sentence on its own. I'd prefer if you could reword this so that reading the body alone makes sense.

**Comment by sschuberth** [comment]
> Add an option to `Npm` to enable this flag on demand, so that NPM 6
> projects with peer dependency conflicts can be analyzed.

Would it make sense to auto-enable this flag only for NPM >= 7, as we already know the NPM version anyway?

**Comment by mnonnenmacher** [comment]
> > Since NPM 7 conflicts in peer dependencies lead to an error during `npm install`, unless the `--legacy-peer-deps` flag is provided [1](https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major).
> 
> I find this sentence hard to understand as it seems to continue the commit message title and is not a sentence on its own. I'd prefer if you could reword this so that reading the body alone makes sense.

The sentence stands on its own, I have added a comma after "7", maybe that makes it clearer to you?

**Comment by mnonnenmacher** [comment]
> > Add an option to `Npm` to enable this flag on demand, so that NPM 6
> > projects with peer dependency conflicts can be analyzed.
> 
> Would it make sense to auto-enable this flag only for NPM >= 7, as we already know the NPM version anyway?



> > Add an option to `Npm` to enable this flag on demand, so that NPM 6
> > projects with peer dependency conflicts can be analyzed.
> 
> Would it make sense to auto-enable this flag only for NPM >= 7, as we already know the NPM version anyway?

I would not enable this by default, also for NPM 6 this error indicates an actual issue, or like the blogpost calls it, a "works by accident" state. So I would rather have users enable this option on purpose.

**Comment by sschuberth** [comment]
> The sentence stands on its own, I have added a comma after "7", maybe that makes it clearer to you?

Ah, that helps, thanks. I was reading the initial "Since" as "As". It would be even clearer if the comma before "unless" would be dropped 😉

**Comment by mnonnenmacher** [comment]
> > The sentence stands on its own, I have added a comma after "7", maybe that makes it clearer to you?
> 
> Ah, that helps, thanks. I was reading the initial "Since" as "As". It would be even clearer if the comma before "unless" would be dropped wink

Done.

**Review by sschuberth — APPROVED** [review]

**Pull request merged**
