### PR TITLE
Introduce a license finding score

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

### CODE REVIEW

**Comment by sschuberth** [comment]
Note that FossID does not seem to have the concept of a "score" to parse for.

**Review by mnonnenmacher — APPROVED** [review]
Adding a test for the score to `AbstractScannerFunTest` would be nice.

**Comment by sschuberth** [comment]
> Adding a test for the score to `AbstractScannerFunTest` would be nice.

I'll look into that separately as that requires some refactoring.

**Comment by sschuberth** [comment]
> > Adding a test for the score to `AbstractScannerFunTest` would be nice.
> 
> I'll look into that separately as that requires some refactoring.

See https://github.com/oss-review-toolkit/ort/pull/5133.

**Pull request merged**
