### PR TITLE
Update the file with an existing Cargo version 

### PR DESCRIPTION
**Pull request by nnobelis**
Please have a look at the individual commit messages for the details.

### CODE REVIEW

**Comment by sschuberth** [comment]
The Cargo update was already done in https://github.com/oss-review-toolkit/ort/pull/7248... but it does not help if no one reviews it 😉

**Comment by nnobelis** [comment]
Closed in favor of https://github.com/oss-review-toolkit/ort/pull/7248.

**Comment by sschuberth** [comment]
Note that the second commit in this PR is probably still valid... you could have just rebased this once #7248 is merged.

**Comment by nnobelis** [comment]
Yes I know, I won't forget.

This commit will piggyback another PR 😄

**Pull request closed without merging**
