### PR TITLE
JAVA version must be 17

### PR DESCRIPTION
**Pull request by chrisdecker1201**
I tried to build it with Java 20 on Windows 10 and wasn't successful.

### CODE REVIEW

**Comment by sschuberth** [comment]
> I tried to build it with Java 20 on Windows 10 and wasn't successful.

Could you be a bit more specific? I recently [fixed](https://github.com/oss-review-toolkit/ort/pull/6632) a Java 19 compile error, so I'd assume any Java 20 fix would be just as simple.

**Comment by sschuberth** [comment]
> I'd assume any Java 20 fix would be just as simple.

Not quite as simple, but here you go: https://github.com/oss-review-toolkit/ort/pull/6940

**Comment by sschuberth** [comment]
Closing this as Java 20 support has been merged. Thanks @chrisdecker1201 anyway for your contribution, and for raising awareness about the Java 20 issues.

**Comment by chrisdecker1201** [comment]
Thank you for fixing this in such short time :)

**Pull request closed without merging**
