### PR TITLE
Update link references of ownership from nexB to aboutcode-org

### PR DESCRIPTION
**Pull request by chinyeungli**

### CODE REVIEW

**Comment by sschuberth** [comment]
Thanks for the contribution @chinyeungli. Could you please share a bit about the logic that this new separation follows? Like, why is https://github.com/nexB/scancode-toolit moved, but e.g. https://github.com/nexB/typecode_libmagic_from_sources not?

Also, the commit message title should follow [Conventional Commits](https://www.conventionalcommits.org/). In this case, I'd use the "docs: " type.

**Comment by chinyeungli** [comment]
@sschuberth Sorry for missing the type in the commit. We are moving all the public repositories from nexB to aboutcode-org. The repository 'typecode_libmagic_from_sources' has now been migrated under aboutcode-org. (The repository, typecode_libmagic_from_sources, simply has not been migrated at the time of your check.)

**Comment by sschuberth** [comment]
> Sorry for missing the type in the commit.

To fix this, you actually need to amend you *existing* commit, not add new ones. Similarly, we don't allow merge commits as part of PRs. If you want to catch-up with latest `main`, please rebase force force-push instead.

So all-in-all, simply squash all your 3 commits into one commit that keeps only the title from the second commit. The body of that commit should contain [this explanation](https://github.com/oss-review-toolkit/ort/pull/9052#issuecomment-2320289785) of yours.

**Comment by chinyeungli** [comment]
Perhaps it's easier to create a new PR.

**Comment by sschuberth** [comment]
> Perhaps it's easier to create a new PR.

Actually, no need for that. Just continue force-pushing to the PR's branch until the history is right 😉

**Pull request closed without merging**
