### PR TITLE
Deterministic builds

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

### CODE REVIEW

**Comment by sschuberth** [comment]
FYI @maxhbr. This way you shouldn't even need `recursiveHash` anymore.

**Comment by maxhbr** [comment]
I will test it

**Comment by maxhbr** [comment]
This fixes the deterministic build issue. If build twice, the hash is `sha256-qv12RfIR75iVnj/UrhottF6oFWZMhplq3hmKrmTo230=` both times. This closes https://github.com/oss-review-toolkit/ort/issues/3958

**Review by fviernau — APPROVED** [review]

**Comment by sschuberth** [comment]
Merging despite the unrelated test failures.

**Comment by sschuberth** [comment]
PS: This change might come in handy in the context of https://reproducible-builds.org/.

**Pull request merged**
