### PR TITLE
examples: Add a README about consulting your legal counsel

### PR DESCRIPTION
**Pull request by sschuberth**
Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

### CODE REVIEW

**Comment by sschuberth** [comment]
@mkurzman, here's the initial text I came up with. Please align with @tsteenbe on the final wording.

**Comment by tsteenbe** [comment]
@sschuberth  We should not call it a disclaimer as that why we have the Apache-2.0 license text for see https://github.com/oss-review-toolkit/ort/blob/master/LICENSE#L143-L151. Prefer to remove any disclaimer wording and make it a softer "Advice"

**Comment by tsteenbe** [comment]
@mkurzman proposed to change the text to:

# Consult your counsel

The ORT configuration files in this directory are provided as examples only. They demonstrate the general
configuartion capabilities of ORT and do not reflect any real-world configuration used by the ORT contributors, nor
are they a recommendation on the configuration to use.

Please consult your legal counsel about how ORT should be configured for your use cases.

**Comment by sschuberth** [comment]
> @mkurzman proposed to change the text to:

Changed.

**Review by tsteenbe — APPROVED** [review]

**Review by tsteenbe — APPROVED** [review]

**Pull request merged**
