### PR TITLE
SpdxDeclaredLicenseMapping: Add 'Amazon Software License'

### PR DESCRIPTION
**Pull request by fviernau**
As found in https://repo.maven.apache.org/maven2/com/amazonaws/amazon-kinesis-client/1.7.5/amazon-kinesis-client-1.7.5.pom,
see also https://github.com/nexB/scancode-toolkit/blob/v3.0.2/src/licensedcode/data/licenses/amazon-sl.LICENSE.

Signed-off-by: Frank Viernau <frank.viernau@here.com>

### CODE REVIEW

**Comment by sschuberth** [comment]
> see also https://github.com/nexB/scancode-toolkit/blob/v3.1.1/src/licensedcode/data/licenses/amazon-sl.LICENSE.

Nit: I believe it makes more sense to refer to ScanCode v3.0.2 here, as that's the version currently used by ORT by default.

**Comment by fviernau** [comment]
> Nit: I believe it makes more sense to refer to ScanCode v3.0.2 here, as that's the version currently used by ORT by default.

@sschuberth agree, changed it.

**Comment by fviernau** [comment]
Merge regardless of the unrelated failure on travis.

**Pull request merged**
