### PR TITLE
Analyzer: Run analyzers with the default IO dispatcher

### PR DESCRIPTION
**Pull request by sschuberth**
Using the default IO dispatcher [1] instead of a custom thread pool
simplifies the code.

[1] https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-dispatchers/-i-o.html

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

### CODE REVIEW

**Comment by sschuberth** [comment]
FYI, this applies the learnings described in https://github.com/oss-review-toolkit/ort/pull/3603 also to the analyzer.

**Comment by oheger-bosch** [comment]
From reading the referenced documentation about `Dispatchers.IO`, I assume that the number of threads available for parallel execution of the analyzer is now higher (64?). Did you run some tests with larger projects to find out whether there is an impact on performance? Memory consumption may be affected as well.

**Comment by mnonnenmacher** [comment]
I wanted to point out the same as @oheger-bosch. Also, the currently used 5 is an arbitrary number, but it was supposed to be made configurable, this change removes that option.

**Comment by sschuberth** [comment]
> Did you run some tests with larger projects to find out whether there is an impact on performance?

I did not run any tests because what we parallelize on is the *different* package managers we analyze. So, e.g. NPM and Maven projects would get analyzed in parallel, but a single multi-module Maven project would not gets its POMs analyzed in parallel. Thus, we should barely ever run into cases where we're even close to 64 threads (as ORT does not even support 64 different package managers at this point). In fact, I doubt we ran into the 5 threads limit in a non-negligible number of cases.

> Also, the currently used 5 is an arbitrary number, but it was supposed to be made configurable, this change removes that option.

Well, actually the number of threads *is* configurable now, via the `kotlinx.coroutines.io.parallelism` system property. Granted, that affects all users of the IO dispatcher, but still, that's IMO an improvement to compared before.

Anyway, I have doubts there's a need / benefit from making this configurable (via ORT options) after all, because so far no one complained about the previous number of `5` to not be configurable.

**Comment by mnonnenmacher** [comment]
> Well, actually the number of threads _is_ configurable now, via the `kotlinx.coroutines.io.parallelism` system property. Granted, that affects all users of the IO dispatcher, but still, that's IMO an improvement to compared before.

Great, can you document this somewhere, maybe in the class docs of the `Analyzer`?

**Review by mnonnenmacher — APPROVED** [review]

**Pull request merged**
