### PR TITLE
Show how to route output to current directory

### PR DESCRIPTION
**Pull request by rrrutledge**
By default the output is written inside the container.
See our [Slack conversation](https://ort-talk.slack.com/archives/C9NNJ54B1/p1686238330683709?thread_ts=1686195720.781609&cid=C9NNJ54B1).

### CODE REVIEW

**Comment by sschuberth** [comment]
Thanks for your contribution @rrrutledge! Please adhere to [Conventional Commits](https://www.conventionalcommits.org/) by prefixing the commit title with `docs: ` and omitting the dot at the end.

**Comment by rrrutledge** [comment]
> Please adhere to [Conventional Commits](https://www.conventionalcommits.org/)

Is it OK to force-push or do I need to start a new branch?

**Comment by sschuberth** [comment]
> Is it OK to force-push or do I need to start a new branch?

Please force-push!

**Review by sschuberth — APPROVED** [review]

**Comment by sschuberth** [comment]
Merging early as all relevant checks for docs passed (and some other checks are expected to fail due to outdated test expectations in this branch).

**Pull request merged**
