### PR TITLE
chore(docker): Upgrade Python to the latest version

### PR DESCRIPTION
**Pull request by fviernau**
This prepares for supporting Python version 3.11.

Note: This is done in a separate (from supporting python 3.11 with Pip) PR in order to show that the existing `PoetryFunTest` does not break for the currently used Python version 3.10, when `poetry` is run under version 3.11.

### CODE REVIEW

**Review by sschuberth — APPROVED** [review]

**Comment by fviernau** [comment]
I'm not sure if this is needed for supporting Python 3.11 with `Pip` / `Poetry` (https://github.com/oss-review-toolkit/ort/pull/7598). I cannot see any indication of need from the tests of that PR. Should we still upgrade Python now, or defer it a bit?

**Comment by sschuberth** [comment]
> Should we still upgrade Python now, or defer it a bit?

I don't have an opinion here as I rarely analyze Python projects. What about @oss-review-toolkit/core-devs?

**Comment by heliocastro** [comment]
Why not give proper instructions how to install multiple pythons with custom docker and done ?
This can be done ion documentation. We already have cases on TNG where i was asked how to have two pythons inside the env.
There's honestly nothing forcing to make 3.11.x default unless we want to have headaches, but in other side, 3.12.x is already banging the door.

**Comment by sschuberth** [comment]
> Why not give proper instructions how to install multiple pythons with custom docker and done ?

To me, bumping the default Python version here simple severs as a proof that our functional tests still pass with that version. It's not exclusively / primarily for convenience of our users.

**Comment by fviernau** [comment]
If one looks at EOL chart, we could establish ORT policy to always support the latest Python version in active support.
In the 3.11 case this will make the analysis work for 3.10 in most of the cases. In cases where it doesn't work (in particular for < 3.10 version, the user has to create a contain with also these Python versions installed to make it work).

So, I vote for a merge.

[1] https://endoflife.date/python

**Pull request merged**
