### PR TITLE
Model: Add support for CPE identifiers

### PR DESCRIPTION
**Pull request by oheger-bosch**
CPEs are an alternative mechanism to identify software components, and
in some areas, e.g. databases for security vulnerabilities, they are
in widespread use. To support use cases in these domains, enable ORT
to store these identifiers if they are available.

This PR is related to #4755.

### CODE REVIEW

**Review by sschuberth — DISMISSED** [review]

**Comment by sschuberth** [comment]
LGTM. Just a question: Shouldn't the first commit message already auto-close #4755?

**Comment by oheger-bosch** [comment]
> LGTM. Just a question: Shouldn't the first commit message already auto-close #4755?

Yes, makes sense. I was not sure, however, to which commit message this should be added. Is the feature already complete in the first commit?

**Comment by oheger-bosch** [comment]
> Well, as the issue is only about the general tracking in the data model, probably yes. But I could understand if you'd feel more comfortable to only add the auto-close to the last commit, as it concludes the series.

Ok, done in the last commit.

**Review by sschuberth — APPROVED** [review]

**Comment by sschuberth** [comment]
Merging this without another test run as only the commit message changed.

**Pull request merged**
