### PR TITLE
chore(docker): Upgrade Conan to version 1.64.1

### PR DESCRIPTION
**Pull request by rettichschnidi**
As of today, version 1.64.1 is the latest 1.x release.

### CODE REVIEW

**Review by fviernau — APPROVED** [review]

**Comment by sschuberth** [comment]
Same here @rettichschnidi, any reason to not make this "Ready for review" yet?

**Comment by rettichschnidi** [comment]
> Same here @rettichschnidi, any reason to not make this "Ready for review" yet?

I made it a habit to only get it out of the draft state when a) CI has passed and b) I am really happy with the state of the PR (as I sometimes just want changes to get out for them to be visible, but before they are actually ready to consume maintainer time).

**Comment by sschuberth** [comment]
> Let me know if this does not work well for you. I can stop it. :)

While b) is fine, a) [is not (always)](https://github.com/oss-review-toolkit/ort/pull/8746#issuecomment-2160851400) 😉

**Comment by sschuberth** [comment]
The `Docker Build` failure is unrelated.

**Pull request merged**
