### PR TITLE
Add linebreak so "==Dependencies" is correctly displayed as headline

### PR DESCRIPTION
**Pull request by hanna-modica**
Fixes the issue seen in below screenshot:

grafik

### CODE REVIEW

**Review by mnonnenmacher — DISMISSED** [review]
Please add a `Signed-off-by:` line to the commit message for the DCO check, see the git log for examples.

**Comment by hanna-modica** [comment]
Hi @mnonnenmacher,
thanks for the hint. Seems I have forgotten to configure it for this project in my IDE. Added it now.

**Comment by sschuberth** [comment]
Unrelated, but the bullets for the list items seems to be broken, too. Is that something you could also fix along the way, @hanna-modica?o

**Review by MarcelBochtler — APPROVED** [review]

**Comment by hanna-modica** [comment]
Hi @sschuberth, thanks for the hint. I think not the bullet points are broken, but the (c)-symbol. So I think the problem maybe lies not in this report template. I will ask the customer who reported this issue to verify, that the fix is working and afterwards confirm, if the wrong display of the character is still there. If yes, I will open a separate issue.

**Comment by MarcelBochtler** [comment]
@hanna-modica This expected test result also needs to be adjusted:
https://github.com/oss-review-toolkit/ort/blob/main/reporter/src/funTest/assets/asciidoc-template-reporter-expected-result.adoc

**Review by MarcelBochtler — CHANGES_REQUESTED** [review]
@hanna-modica This expected test result also needs to be adjusted:
https://github.com/oss-review-toolkit/ort/blob/main/reporter/src/funTest/assets/asciidoc-template-reporter-expected-result.adoc

**Review by MarcelBochtler — APPROVED** [review]

**Pull request merged**
