### PR TITLE
PostgresStorage: Read only one result per provenance and scanner details

### PR DESCRIPTION
**Pull request by fviernau**
The scan storage handling is currently implemented such that multiple
scan results may get store for a single idendifier, scanner details
provenance tuple. This situation is infact not unlikely as the time
interval between (1) the look-up of a stored scan result for a package
and (2) the actual scan executed due to the failed look-up may be
relatively large. I've observerd this interval to span more than three
hours and the scan storage I'm using for some packages has even six
equal scan results which all do end-up in the OrtResults, increasing its
size unnecessarily.

While the above mentioned time interval should be reduced, and ideally
also should be made impossible that multiple scan results with equal
identifier, provenance and scanner details cannot be stored in the first
place, this change ensures that such duplicates are not put into
OrtResults and are not even transferred from the database, by querying
only the most recent matching VCS and source artifact scan.

Signed-off-by: Frank Viernau <frank.viernau@here.com>

### CODE REVIEW

**Comment by sschuberth** [comment]
> scan results may get store for a single idendifier, scanner details

"stored", "identifier"

> provenance tuple. This situation is infact not unlikely as the time

"in fact"

> relatively large. I've observerd this interval to span more than three

"observed"

> also should be made impossible that multiple scan results with equal

"it also"

> identifier, provenance and scanner details cannot be stored in the first

"can be stored" as you say that should be impossible

**Comment by sschuberth** [comment]
I'll leave the content-related review to @mnonnenmacher as he's the most knowledgeable about this area of code.

**Comment by fviernau** [comment]
@sschuberth after looking deeper into the failing tests and after re-writing the query to not make the tests fail it turns out that the query becomes quite complex, which is why I propose to do #2850 instead.

**Comment by sschuberth** [comment]
> @sschuberth after looking deeper into the failing tests and after re-writing the query to not make the tests fail it turns out that the query becomes quite complex, which is why I propose to do #2850 instead.

So, good to close this one then?

**Comment by fviernau** [comment]
> So, good to close this one then?

Yes!

**Pull request closed without merging**
