### PR TITLE
fix(fossid-webapp): Add missing license category

### PR DESCRIPTION
**Pull request by nnobelis**

### CODE REVIEW

**Comment by nnobelis** [comment]
> Does a similar rationale as for [f63e655](https://github.com/oss-review-toolkit/ort/commit/f63e6550ee7f6fdab817946de39eeb982e9523ea) apply? If so, please add it to the commit message.

I am not sure.
https://github.com/oss-review-toolkit/ort/commit/f63e6550ee7f6fdab817946de39eeb982e9523ea had this comment because a new property was added to `IdentifiedFile`.

Here, we are receiving a new license category: I don't know if this is because of the new FossID version, new Knowledge Base version or something changed something in the code being scanned that triggers this (previously) unseen license category.

Therefore I won't make assumption.

**Comment by sschuberth** [comment]
> I don't know if this is because of the new FossID version, new Knowledge Base version or something changed something in the code being scanned that triggers this (previously) unseen license category.

But having exactly this sentence (reworded in passive voice) in the commit message would already be valuable (and avoid the need to answer my questions 😉 ).

**Comment by nnobelis** [comment]
> > I don't know if this is because of the new FossID version, new Knowledge Base version or something changed something in the code being scanned that triggers this (previously) unseen license category.
> 
> But having exactly this sentence (reworded in passive voice) in the commit message would already be valuable (and avoid the need to answer my questions 😉 ).

Done.

**Review by sschuberth — APPROVED** [review]

**Comment by sschuberth** [comment]
BTW, does this enum apply sorting of some kind? If not, does it make sense to sort alphabetically?

**Comment by nnobelis** [comment]
What do you mean with "apply sorting" ?

**Comment by sschuberth** [comment]
> What do you mean with "apply sorting" ?

Nevermind, I was confused by the inline annotation comments shown in the diff. The enum values are already sorted alphabetically.

**Pull request merged**
