### PR TITLE
SpdxDocumentFile: Properly handle multiple package.spdx.xml files

### LINKED ISSUE #3833: SpdxDocumentFile handles package.spdx.yml incorrectly, leading to broken analyzer run
As discover by @heliocastro, the SpdxDocumentFile fails when more than one package.spdx.yml is in the directory or a subdirectory:
```
13:31:17.026 [DefaultDispatcher-worker-3] ERROR org.ossreviewtoolkit.analyzer.AnalyzerResultBuilder - Multiple projects with the same id 'SpdxDocumentFile:::' found. Not adding the project defined in '/' to the analyzer results as it duplicates the project defined in '/'.
```

This is due to creating an EMPTY Project [1] when a package.spdx.yml is passed in as a definition file. If there is more than one package.spdx.yml it leads to multiple projects having the same ID. 

Handling package.spdx.yml needs to be improved:

https://github.com/oss-review-toolkit/ort/blob/dee26a1e2d7e26ac448878a49f1becc4c5ccbb71/analyzer/src/main/kotlin/managers/SpdxDocumentFile.kt#L458-L460

### PR DESCRIPTION
**Pull request by sschuberth**
Actually, the analyzer should not directly look for / handle SPDX
documents that describe a package instead of a project. Instead, only
projects should be handled, and packages are implicitly handled when
they are referred to from the project.

Resolves #3833.

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

### CODE REVIEW

**Comment by neubs-bsi** [comment]
Corresponding issue: #3833

**Comment by sschuberth** [comment]
> Corresponding issue: #3833

:+1: I've amended the commit message.

**Review by neubs-bsi — APPROVED** [review]

**Review by neubs-bsi — COMMENTED** [review]
You could remove the description of "This resolves the issue..." now that you have linked the issue.

**Review by neubs-bsi — APPROVED** [review]

**Review by oheger-bosch — APPROVED** [review]
The changes look good. The only thing I noticed is that in the `mapDefinitionFiles()` function all definition files are read. Later, when resolving the dependencies, the remaining definition files are read again. So, as a future performance optimization, it could make sense to cache the the results of the read operations somehow.

**Comment by sschuberth** [comment]
> So, as a future performance optimization, it could make sense to cache the the results of the read operations somehow.

Good point, I'll do that as a follow-up PR.

**Review by heliocastro — APPROVED** [review]
Tested on two set of projects beyond the test reference repo.
All worked satisfactory.
Please commit

**Comment by sschuberth** [comment]
> Please commit

Already done 😁 Thanks for testing.

**Comment by sschuberth** [comment]
> > So, as a future performance optimization, it could make sense to cache the the results of the read operations somehow.
> 
> Good point, I'll do that as a follow-up PR.

See https://github.com/oss-review-toolkit/ort/pull/3849.

**Pull request merged**
