### PR TITLE
Scancode : upgrade to version 3.2.3

### PR DESCRIPTION
**Pull request by fb33**
Please ensure that your pull request adheres to our [contribution guidelines](../CONTRIBUTING.md). Thank you!

### CODE REVIEW

**Comment by mnonnenmacher** [comment]
@oheger-bosch @sschuberth @fviernau I have tested this change and realized that against my expectation it would invalidate all scan results for the previous version 3.2.1-rc2 without manually configuring a `minVersion`. What would think of changing the code below to not set the default value `minVersion` to the current version but to $major.$minor.0 (in this case 3.2.0) instead? This would mean that by default we accept all scan result for the same major.minor version and ignore the patch level which you could always override by manually defining `minVersion` and `maxVersion`.

https://github.com/oss-review-toolkit/ort/blob/d4e616079b0afd8f5f623e50124324b90d9890b3/scanner/src/main/kotlin/LocalScanner.kt#L194-L200

**Comment by sschuberth** [comment]
> What would think of changing the code below

Actually, instead of doing that I'd prefer to drive https://github.com/oss-review-toolkit/ort/pull/3518 forward and ensure that it would match our use-case from here.

**Comment by mnonnenmacher** [comment]
> Actually, instead of doing that I'd prefer to drive #3518 forward and ensure that it would match our use-case from here.

That PR does not change the defaults used for version matching.

**Comment by sschuberth** [comment]
> That PR does not change the defaults used for version matching.

Correct. But it lays the foundation for generalizing the scanner compatibility checks, including version matching, as [discussed here](https://github.com/oss-review-toolkit/ort/issues/3223#issuecomment-763419529).

**Comment by oheger-bosch** [comment]
@mnonnenmacher, I support your idea of changing the default for the minimum accepted scanner version. Ignoring the patch level in version checks probably makes sense most of the time.

As #3518 has some changes in this area, I would prefer to address this after this PR has been merged.

**Comment by mnonnenmacher** [comment]
I have added the breaking change label, because without implementing the changes discussed above this change would require either a configuration change or re-scanning of all packages.

**Comment by tsteenbe** [comment]
@mnonnenmacher  @oheger-bosch  Propose we update this PR to use the newer [v21.2.9](https://github.com/nexB/scancode-toolkit/releases/tag/v21.2.9) so we don't break things twice in a short time for our users.

**Pull request closed without merging**
