### PR TITLE
cli: Move Constants and Extensions to the utils package

### PR DESCRIPTION
**Pull request by sschuberth**
These are not commands.

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

### CODE REVIEW

**Review by oheger-bosch — DISMISSED** [review]

**Review by MarcelBochtler — CHANGES_REQUESTED** [review]
You need to add imports for extensions used in `AdvisorCommand`, `AnalyzerCommand`, `DownloaderCommand` and some more.

**Review by MarcelBochtler — COMMENTED** [review]
`./gradlew :cli:compileFunTestKotlin` is still failing.
But I'm not sure why, as I see that you added the imports.

**Comment by sschuberth** [comment]
> `./gradlew :cli:compileFunTestKotlin` is still failing.
> But I'm not sure why, as I see that you added the imports.

Thanks, I believe it's due to some subtle package name clash. I'll try to resolve it in a preparing commit.

**Review by MarcelBochtler — APPROVED** [review]
LGTM.

However, this requires every developer to change their Run configurations (`cli.OrtMainKt`). You might want to announce this in the Slack channel.
Also `./gradlew detekt` fails for me locally, but CI seems to be fine with it.

**Comment by sschuberth** [comment]
> However, this requires every developer to change their Run configurations (Main Class: `org.ossreviewtoolkit.cli.OrtMainKt`). You might want to announce this in the Slack channel.

Good point. Do you thin this deserves a "breaking change" label?

> Also `./gradlew detekt` fails for me locally, but CI seems to be fine with it.

There is a glitch with our detekt-rules not being rebuilt correct, it seems, but I had no time to look into it.

**Comment by MarcelBochtler** [comment]
> Do you think this deserves a "breaking change" label?

From my understanding this label is only required if user facing configurations / functionalities change.
IMO developers are not users therefore the label is not required.

**Comment by MarcelBochtler** [comment]
> There is a glitch with our detekt-rules not being rebuilt correct, it seems, but I had no time to look into it.

Do you know a work around to fix it?
Cleaning and rerunning tasks seems not to work.

**Comment by sschuberth** [comment]
> Do you know a work around?

Yes, `rm ./detekt-rules/build/libs/detekt-rules.jar` should do the trick.

**Comment by sschuberth** [comment]
> There is a glitch with our detekt-rules not being rebuilt correct, it seems, but I had no time to look into it.

I'll try to look into it tonight.

**Comment by sschuberth** [comment]
> > Also `./gradlew detekt` fails for me locally, but CI seems to be fine with it.
> 
> There is a glitch with our detekt-rules not being rebuilt correct, it seems, but I had no time to look into it.

Looks like this is a [known issue](https://github.com/detekt/detekt/issues/2645#issuecomment-622217315) with custom *detekt* rules and the Gradle daemon / Java's `ServiceLoader` 😢

**Pull request merged**
