### PR TITLE
GoMod: Drop the "all" scope, simplify and clean-up a bit

### PR DESCRIPTION
**Pull request by fviernau**
See individual commits.

Eliminate over-reporting of dependencies I discovered while investigating #5021.

### CODE REVIEW

**Review by mnonnenmacher — DISMISSED** [review]

**Comment by sschuberth** [comment]
Just a general question @fviernau: With all those recent changes to the expected results happening, do you compare the new expected results to what some other tool reports? Like maybe any of [these](https://github.com/oss-review-toolkit/ort/wiki/Related-Tools#open-source-tools) which also offer Golang dependency analysis?

**Comment by fviernau** [comment]
> Just a general question @fviernau: With all those recent changes to the expected results happening, do you compare the new expected results to what some other tool reports? Like maybe any of [these](https://github.com/oss-review-toolkit/ort/wiki/Related-Tools#open-source-tools) which also offer Golang dependency analysis?

So far, I've been relying on the output of the command line tools of `go` as well as their documentation.
Anyhow, I'll see for my upcoming PRs whether I can double check using these tools. One of them looked suitable on the first glance.

**Review by mnonnenmacher — APPROVED** [review]

**Comment by fviernau** [comment]
> Just a general question @fviernau: With all those recent changes to the expected results happening, do you compare the new expected results to what some other tool reports? Like maybe any of [these](https://github.com/oss-review-toolkit/ort/wiki/Related-Tools#open-source-tools) which also offer Golang dependency analysis?

@sschuberth as you seem interested in it: I just compared the results (for our synthetic project) against the ones from:
 
1. fossa, which also accidentally over-reports similar as ORT did before this PR. See https://github.com/fossas/fossa-cli/issues/980
2. snyk, which yields the exact same results as ORT after merging this PR

**Comment by sschuberth** [comment]
> I just compared the results (for our synthetic project)

Thanks! That's interesting and somewhat relieving information (ping also @mkurzman).

**Pull request merged**
