### PR TITLE
Support OSS Index as a vulnerability provider

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

### CODE REVIEW

**Comment by oheger-bosch** [comment]
Note that there are conflicting parts with #4493.

**Comment by sschuberth** [comment]
> Note that there are conflicting parts with #4493.

Yes, thanks for pointing that out. If not too much work for you, I'd prefer to get this merged first, as it had been pending for a long time, and could serve as another implementation to double-check the new model.

**Review by oheger-bosch — APPROVED** [review]
I would love to see a (Wiremock-) test for this new advisor implementation. This would also include sample responses from the service, helping to better understand the model used behind the scenes.

**Comment by sschuberth** [comment]
> I would love to see a (Wiremock-) test for this new advisor implementation.

Can we do this together quickly next week as a follow-up?

**Comment by sschuberth** [comment]
> > I would love to see a (Wiremock-) test for this new advisor implementation.
> 
> Can we do this together quickly next week as a follow-up?

Done in https://github.com/oss-review-toolkit/ort/pull/4507.

**Pull request merged**
