### PR TITLE
Change all namespaces from com.here to org.ossreviewtoolkit

### PR DESCRIPTION
**Pull request by sschuberth**
This reflects ORT now being an independent Linux Foundation project in
its own GitHub organization at [1], with a homepage URL of [2].

[1] https://github.com/oss-review-toolkit/ort
[2] http://ossreviewtoolkit.org

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

### CODE REVIEW

**Comment by sschuberth** [comment]
@mnonnenmacher any good idea how to bulk-fix import ordering according to our rules (alphabetical ordering with blank lines between groups)? *ktlint* (and thus *detekt*) enforce [no blank lines between major groups](https://github.com/pinterest/ktlint/blob/a86d1c76c44d0a1c1adc3f756f36d8b4cac15d32/ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/ImportOrderingRule.kt#L11).

**Comment by mnonnenmacher** [comment]
> @mnonnenmacher any good idea how to bulk-fix import ordering according to our rules (alphabetical ordering with blank lines between groups)? _ktlint_ (and thus _detekt_) enforce [no blank lines between major groups](https://github.com/pinterest/ktlint/blob/a86d1c76c44d0a1c1adc3f756f36d8b4cac15d32/ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/ImportOrderingRule.kt#L11), and [IntelliJ's import ordering is even worse](https://github.com/pinterest/ktlint/issues/527).

I don't know any existing solution, but writing a custom script that orders the imports according to our rules should not be too hard, it could even be a Gradle task so that we can reuse it later. This might be useful when doing bigger changes, or it could be used as a CI check.

**Comment by sschuberth** [comment]
> it could even be a Gradle task so that we can reuse it later.

I'd actually prefer another custom detekt rule. But would you be fine with merging this now and fixing import ordering later?

**Comment by mnonnenmacher** [comment]
> But would you be fine with merging this now and fixing import ordering later?

Yes, but I need to test this with our pipeline first, I expect that we need to update some scripts, I'll approve and merge when I have prepared the required changes.

**Pull request merged**
