### PR TITLE
docs(Adopters): Add HELLA Aglaia

### PR DESCRIPTION
**Pull request by pepper-jk**
Just adding us to the Adopters list, which was long overdue.

Signed-off-by: Jens Keim <jens.keim@forvia.com>

### CODE REVIEW

**Review by fviernau — DISMISSED** [review]

**Review by tsteenbe — DISMISSED** [review]

**Comment by sschuberth** [comment]
Not sure why the [dead link check fails with 403](https://github.com/oss-review-toolkit/ort/actions/runs/12259241725/job/34205632159?pr=9576#step:4:45) on https://hella-aglaia.com/... is there another link we could use @pepper-jk?

**Comment by sschuberth** [comment]
> Not sure why the [dead link check fails with 403](https://github.com/oss-review-toolkit/ort/actions/runs/12259241725/job/34205632159?pr=9576#step:4:45) on https://hella-aglaia.com/...

I hope to get this fixed with https://github.com/oss-review-toolkit/ort/pull/9578.

**Comment by pepper-jk** [comment]
> Not sure why the [dead link check fails with 403](https://github.com/oss-review-toolkit/ort/actions/runs/12259241725/job/34205632159?pr=9576#step:4:45) on https://hella-aglaia.com/... is there another link we could use @pepper-jk?

We could try our parent company: https://www.hella.com
Would that be OK, @jens-erdmann ?

> I hope to get this fixed with https://github.com/oss-review-toolkit/ort/pull/9578.

Okay, that would be preferable. If not I can try the alternative domain tomorrow, to see if it would technically work.

**Comment by sschuberth** [comment]
@pepper-jk please rebase and resolve conflicts.

**Comment by jens-erdmann** [comment]
> > Not sure why the [dead link check fails with 403](https://github.com/oss-review-toolkit/ort/actions/runs/12259241725/job/34205632159?pr=9576#step:4:45) on https://hella-aglaia.com/... is there another link we could use @pepper-jk?
> 
> We could try our parent company: https://www.hella.com Would that be OK, @jens-erdmann ?
> 
> > I hope to get this fixed with #9578.
> 
> Okay, that would be preferable. If not I can try the alternative domain tomorrow, to see if it would technically work.

Should be fine. Not sure why we get errors on the first one.

**Review by sschuberth — APPROVED** [review]

**Comment by pepper-jk** [comment]
The FunTest failing should be unrelated to the changes.
Should be ready for merge.

**Comment by pepper-jk** [comment]
Since it can not auto-merge with the failing FunTest, it needs a manual merge.
I would prefer to force push again with my PGP signature first though, if that is alright we you.

**Comment by sschuberth** [comment]
> Since it can not auto-merge with the failing FunTest, it needs a manual merge.

The test in question was already fixed. What we now saw on the last run was just test flakyness.

> I would prefer to force push again with my PGP signature first though, if that is alright with you.

Fine with me.

**Pull request merged**
