### PR TITLE
fix(model): Keep the old "options" as a alias for "config"

### PR DESCRIPTION
**Pull request by sschuberth**
This is a fixup for 712c448 to allow for deserializing older results.

### CODE REVIEW

**Review by fviernau — APPROVED** [review]

**Comment by fviernau** [comment]
It could that that the failing PipFunTest results from https://github.com/oss-review-toolkit/ort/pull/7695 for which I just noticed, the docker fun tests have been skipped.

**Comment by sschuberth** [comment]
> It could be that the failing PipFunTest results from #7695 for which I just noticed, the docker fun tests have been skipped.

Thanks for the hint, I'll have a look.

**Comment by sschuberth** [comment]
Merging despite the unrelated `PipFunTest` failure.

**Comment by fviernau** [comment]
> Thanks for the hint, I'll have a look.

We may temporarily revert that commit. I've filed https://github.com/oss-review-toolkit/ort/pull/7699 to see if it fixes the problem.

**Comment by mnonnenmacher** [comment]
@sschuberth I didn't introduce the alias as not only the name but also the structure was changed, so the only case where this might help is if the old `options` are set to an empty map.

**Comment by sschuberth** [comment]
> so the only case where this might help is if the old `options` are set to an empty map.

I was just double-checking the result that failed to load for me, and you're right, it looks like

```
  config:
    skip_concluded: false
    create_missing_archives: false
    detected_license_mapping:
      LicenseRef-scancode-agpl-generic-additional-terms: "NOASSERTION"
      LicenseRef-scancode-generic-cla: "NOASSERTION"
      LicenseRef-scancode-generic-exception: "NOASSERTION"
      LicenseRef-scancode-generic-export-compliance: "NOASSERTION"
      LicenseRef-scancode-generic-tos: "NOASSERTION"
      LicenseRef-scancode-generic-trademark: "NOASSERTION"
      LicenseRef-scancode-gpl-generic-additional-terms: "NOASSERTION"
      LicenseRef-scancode-patent-disclaimer: "NOASSERTION"
      LicenseRef-scancode-warranty-disclaimer: "NOASSERTION"
      LicenseRef-scancode-other-copyleft: "NOASSERTION"
      LicenseRef-scancode-other-permissive: "NOASSERTION"
      LicenseRef-scancode-free-unknown: "NOASSERTION"
      LicenseRef-scancode-unknown: "NOASSERTION"
      LicenseRef-scancode-unknown-license-reference: "NOASSERTION"
      LicenseRef-scancode-unknown-spdx: "NOASSERTION"
    options: {}
    ignore_patterns:
    - "**/*.ort.yml"
    - "**/*.spdx.yml"
    - "**/*.spdx.yaml"
    - "**/*.spdx.json"
    - "**/META-INF/DEPENDENCIES"
    - "**/META-INF/DEPENDENCIES.txt"
    - "**/META-INF/NOTICE"
    - "**/META-INF/NOTICE.txt"
```

So, should I revert this?

**Comment by mnonnenmacher** [comment]
I'm not sure, I mean in this case it did help, so maybe it's worth it.

**Comment by sschuberth** [comment]
> I'm not sure, I mean in this case it did help, so maybe it's worth it.

Yeah, I was thinking the same; I wouldn't have done it if I didn't had a concrete problem. So let's keep it for now, and clean it up in one of the occasional legacy-stuff-removal cycles.

**Pull request merged**
