### PR TITLE
OsvFunTest: Update expected test results

### PR DESCRIPTION
**Pull request by sschuberth**
Add more references and reorder results as expected.

Signed-off-by: Sebastian Schuberth <sschuberth@gmail.com>

### CODE REVIEW

**Review by oheger-bosch — APPROVED** [review]
Can it be that this test requires updates very frequently?

**Comment by sschuberth** [comment]
> Can it be that this test requires updates very frequently?

At least recently, yes. Maybe it's not a good idea to use NPM packages for vulnerability tests, as these have new findings all the way long 😉

**Comment by fviernau** [comment]
> Yes, different package could help. Any recommendations for the ecosystem / package to use?

Or refactoring the test so that it checks that the expected vulnerabilities are contained in the result instead of an equality check.  I'll take care of making it less flaky soon. IIRC I've chosen older versions of the package with the hope that vulnerabilities don't change too often.

**Comment by sschuberth** [comment]
> Any recommendations for the ecosystem / package to use?

Anything Rust / Cargo maybe?

**Pull request merged**
