### PR TITLE
ScanResult: Remove raw result

### LINKED ISSUE #3403: Remove code to write out the raw scan result as a separate file
As we have the reporter tool for a long time, this code can probably be removed:

https://github.com/oss-review-toolkit/ort/blob/725c10d2653cc0cc55e8c319e298c77668b92308/scanner/src/main/kotlin/LocalScanner.kt#L339-L344

@mnonnenmacher will check HERE internally.

### PR DESCRIPTION
**Pull request by mnonnenmacher**
Remove the `rawResult` field from the `ScanResult`. The property
contained the raw data from the license scanner. The idea behind this
property was that it might be useful to have the raw data, but in
practice it turned out it is very rarely used. The raw result could be
much larger than the `ScanSummary` which contains the extracted data
from the raw result. This significantly increased the space required for
storing scan results and also slowed down storing and reading scan
results from a storage, for no practical use. This change also reduces
the amount of memory used by the scanner, because raw results are kept
in memory for a shorter time when scanning packages, and not at all when
downloading scan results from the storage.

Fixes #3403: As part of this also an old workaround that stored the raw
results in separate files is removed.

### CODE REVIEW

**Review by sschuberth — APPROVED** [review]

**Review by fviernau — APPROVED** [review]

**Review by fviernau — APPROVED** [review]

**Review by sschuberth — APPROVED** [review]

**Comment by nnobelis** [comment]
I think this is an error to remove the raw results.

For FossID scanner for instance, there are some concepts that don't translate in ORT license/copyright findings : ignored files + ignored cause, files marked as identified and files automatically identified.
I was hoping to use the raw results to carry these information.

**Comment by nnobelis** [comment]
Additionaly @mnonnenmacher you said in [another ticket](https://github.com/oss-review-toolkit/ort/pull/3105#discussion_r497338975) that raw results are for carrying this kind of extra information :

**Comment by mnonnenmacher** [comment]
@nnobelis To me the main question is what is the purpose of recording that data.
If it will not be used by ORT anywhere and is just recorded for reference or for use by a third-party tool, then an "untyped" property like a `JsonNode` or a `Map<String, Any>` might be ok, but in this case a new property should be added instead of the `rawResult`, because `rawResult` should contain only the complete unmodified output from the scanner. In the case that ORT will somehow use this data, and may it be only to show it in a report which would make sense for the "ignord files + cause" data you mention above, it should have a proper model to make it easily accessible to all components. For example a new property `ScanSummary.ignoredFiles: List<IgnoredFile>` with `data class IgnoredFile(val path: String, val cause: String)`. And if possible that property should also be implemented for other scanners that have a similar feature.

**Comment by sschuberth** [comment]
IIRC we "misused" the raw result to capture snippet-scanner type of data [for which we do not yet have a data model in ORT](https://github.com/oss-review-toolkit/ort/issues/3265). So in my view it was a temporary solution until the linked discussion was resolved. So for us, if we remove the raw result now, we quickly need to settle on a solution for the snippet scanner data model discussion.

**Comment by mnonnenmacher** [comment]
@sschuberth  Yes, let's rather find the model for the snippet scanner. So would it be ok from your side to merge this now?

**Comment by sschuberth** [comment]
> So would it be ok from your side to merge this now?

From my side, yes. If needed, we'll stick to a branch which still has the raw result. @nnobelis do you agree?

**Comment by nnobelis** [comment]
yes you can merge it.

**Pull request merged**
