### PR TITLE
Add a PR template the reminds one to write good commit messages

### PR DESCRIPTION
**Pull request by sschuberth**
Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

### CODE REVIEW

**Comment by sschuberth** [comment]
@mnonnenmacher @fviernau how about doing this as an experiment?

**Comment by mnonnenmacher** [comment]
> @mnonnenmacher @fviernau how about doing this as an experiment?

I like that idea, but we should also add a link to the CONTRIBUTING.md because it contains more guidelines about PRs.

**Comment by sschuberth** [comment]
> I like that idea, but we should also add a link to the CONTRIBUTING.md because it contains more guidelines about PRs.

Done.

**Comment by mnonnenmacher** [comment]
> > I like that idea, but we should also add a link to the CONTRIBUTING.md because it contains more guidelines about PRs.
> 
> Done.

What I actually meant was to add a link to the template that points to CONTRIBUTING.md, to remind people to read that first. But we can add that later as well.

**Comment by mnonnenmacher** [comment]
@sschuberth  If we add that template, will GitHub still use the commit message as PR message for single commit PRs?

**Comment by sschuberth** [comment]
> What I actually meant was to add a link to the template that points to CONTRIBUTING.md, to remind people to read that first. But we can add that later as well.

Ah, I though we'd rely on GitHub's [feature](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors) to automatically do this, at least for first-time contributors. But you're right, it seems a bit arbitrary to only quite parts of `CONTRIBUTING.md` but not the file itself.

So, should we always link to `CONTRIBUTING.md` only?

**Comment by sschuberth** [comment]
> 
> 
> @sschuberth If we add that template, will GitHub still use the commit message as PR message for single commit PRs?

That's one of the things I wanted to try out after the merge. But I guess I could also create a dummy PR with this PR as the target branch...

**Comment by mnonnenmacher** [comment]
> > What I actually meant was to add a link to the template that points to CONTRIBUTING.md, to remind people to read that first. But we can add that later as well.
> 
> Ah, I though we'd rely on GitHub's [feature](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors) to automatically do this, at least for first-time contributors. But you're right, it seems a bit arbitrary to only quite parts of `CONTRIBUTING.md` but not the file itself.
> 
> So, should we always link to `CONTRIBUTING.md` only?

Yes, I think that would be best, then we don't have to repeat ourselves.

**Comment by sschuberth** [comment]
> Yes, I think that would be best, then we don't have to repeat ourselves.

Done.

**Review by mnonnenmacher — APPROVED** [review]

**Comment by sschuberth** [comment]
> @sschuberth If we add that template, will GitHub still use the commit message as PR message for single commit PRs?

Yes, it will look like this:

2020-11-18_09h15_15

**Pull request merged**
