### PR TITLE
Testing adding a comment to a Gemfile

### PR DESCRIPTION
**Pull request by lancedikson**
TBD if the test works out
Please ensure that your pull request adheres to our [contribution guidelines](https://github.com/oss-review-toolkit/.github/blob/main/CONTRIBUTING.md). Thank you!

### CODE REVIEW

**Comment by sschuberth** [comment]
I guess this PR related to [this comment](https://github.com/oss-review-toolkit/ort/issues/7478#issuecomment-2108588425) of yours. I ran the same test locally (as that's much faster) and it passes for me.

**Comment by sschuberth** [comment]
> I guess this PR related to [this comment](https://github.com/oss-review-toolkit/ort/issues/7478#issuecomment-2108588425) of yours. I ran the same test locally (as that's much faster) and it passes for me.

Interesting, in CI it seems to fail. I'll investigate.

**Comment by lancedikson** [comment]
> I guess this PR related to https://github.com/oss-review-toolkit/ort/issues/7478#issuecomment-2108588425 of yours.

Yes, sorry for not linking the PR with the issue proactively

> Interesting, in CI it seems to fail. I'll investigate.

Thanks! 🙌 Though the problem is hardly related to the open issue, but most likely to [the comment only](https://github.com/oss-review-toolkit/ort/issues/7478#issuecomment-1969987962).

**Comment by sschuberth** [comment]
> Thanks! 🙌 Though the problem is hardly related to the open issue, but most likely to [the comment only](https://github.com/oss-review-toolkit/ort/issues/7478#issuecomment-1969987962).

Actually, I can reproduce the problem also without the comment, so it's not related to that (and explains why I could not reproduce the problem by just adding a comment to an existing file). Instead, the problem seems to be related to the `github` dependency type.

**Comment by lancedikson** [comment]
Okay, interesting :) It somehow works without a comment for me in my actual project and doesn't work with a comment. That's why I thought it was a comment-related issue.

**Comment by sschuberth** [comment]
Digging deeper, looks like this is related to Ruby calling native `git` to fetch from GitHub underneath, and then running into https://github.com/jruby/jruby/issues/6721. Actually, we already apply some of the work-arounds mentioned there. I'll investigate why they seem to have no effect.

**Comment by sschuberth** [comment]
> and then running into [jruby/jruby#6721](https://github.com/jruby/jruby/issues/6721).

That was a red herring. The real cause was slightly different leading console output when fetching from GitHub, and that output was not stripped properly before parsing. https://github.com/oss-review-toolkit/ort/pull/8644 fixes this.

**Comment by lancedikson** [comment]
Thanks! I'll test it with my project today.

**Pull request closed without merging**
