### PR TITLE
fix(Poetry): Fix the broken analysis if a "dev" dependency group does not exist

### LINKED ISSUE #7679: Poetry: analyse fails if dev group dependency isn't present
ORT fails to analyse a python project using poetry package manager that don't defines dev dependency group.

```
20:30:13.172 [DefaultDispatcher-worker-1] ERROR java.lang.Object - Poetry failed to resolve dependencies for path 'poetry.lock': IOException: Running 'poetry export --without-hashes --format=requirements.txt --only=dev' in '/project' failed with exit code 1:

Group(s) not found: dev (via --only)
```

Slack [thread](https://ort-talk.slack.com/archives/C9NNJ54B1/p1696974335286449)

### PR DESCRIPTION
**Pull request by fviernau**
See individual commits.

Fixes #7679.

### CODE REVIEW

**Review by heliocastro — APPROVED** [review]
Looks good to me

**Comment by sschuberth** [comment]
What do you think about a different approach that would also have the benefit that other dependency groups than "main" and "dev" would be supported: Instead of hard-coding the original

    private val SCOPES_NAMES = listOf("main", "dev")

scope names would be determined by a trivial parser for `pyproject.toml` that looks for `[tool.poetry.group.<name>.dependencies]` entries, and all `<name>`s would go into the list of scope names.

**Comment by fviernau** [comment]
> What do you think about a different approach that would 

Makes sense to me on the first glance. However, in scope of this PR I prefer to not change the approach and only fix the bug. So, I'd like to keep it as-is. Changing the approach can be done in a following iteration.

**Comment by sschuberth** [comment]
> Changing the approach can be done in a following iteration.

Would you then revert the revert commit, and all changes on top of it? That does seem meaningful to me. Because the proposed solution is a simple and clean addition to the current code, which probably totals in less code than this solution.

**Comment by fviernau** [comment]
> Would you then revert the revert commit, and all changes on top of it? That does seem meaningful to me. Because the proposed solution is a simple and clean addition to the current code, which probably totals in less code than this solution.

Once I do this implementation, I can do that revert approach at your preference.

**Comment by sschuberth** [comment]
> Once I do this implementation, I can do that revert approach at your preference

So, if we agree that my proposed solution makes sense and that it's easy to implement, why should we then bother to temporarily have the solution from this PR in our Git history?

**Comment by fviernau** [comment]
> So, if we agree that my proposed solution makes sense and that it's easy to implement, why should we then bother to temporarily have the solution from this PR in our Git history?

I've been contributing a bug fix, not a new solution. Your proposal extends the scope beyond fixing this bug, which is additional work. So the reason is that I'm not willing to implement a new approach right now, but I'm willing to fix the bug I just introduced.

**Comment by sschuberth** [comment]
> I've been contributing a bug fix, not a new solution.

If we can get both more cheaply than just the fix, I don't see why we shouldn't.

> I like to switch to your proposed approach once fits my schedule better.

See https://github.com/oss-review-toolkit/ort/pull/7691 for my proposal (which took me less time to code than waiting for your answer in this discussion; however, only because I could use your test 😉 ).

**Comment by fviernau** [comment]
> If we can get both more cheaply than just the fix, I don't see why we shouldn't.

I'm not following your definition of more cheaply. It's certainly not cheaper than just clicking the merge button as this was already tested, both with functional tests and manually by the bug reporter.

**Comment by sschuberth** [comment]
> I'm not following your definition of more cheaply.

Writing the new solution was quicker than following up on this PR discussion. That's what I mean with "more cheaply".

**Comment by fviernau** [comment]
> Writing the new solution was quicker than following up on this PR discussion. That's what I mean with "more cheaply".

I see,  you mean "more cheaply" for you...

**Comment by sschuberth** [comment]
> I see, you mean "more cheaply" for you...

I'm not getting your point. Of course you've invested more work into this than me initially as it was you proposing the change. But I've also invested significant amounts of my (unpaid, in contrast to you) time in the review and the discussion with you. Both of us wasted a lot of time arguing over whether we should take an inferior solution just because it's already there, instead of investing a fraction of the discussion time to implement a superior solution.

**Comment by fviernau** [comment]
Closing as replaced by https://github.com/oss-review-toolkit/ort/pull/7691

**Pull request closed without merging**
