### PR TITLE
Gradle: Rename core-utils to ort-utils

### PR DESCRIPTION
**Pull request by mnonnenmacher**
In an upcoming change the `model` module will be renamed to `core`.
Rename `core-utils` to `ort-utils` to avoid confusion, and to emphasize
that the module contains ORT specific utilities.

### CODE REVIEW

**Comment by sschuberth** [comment]
> In an upcoming change the `model` module will be renamed to `core`.

Did we really want to rename, or split? I don't recall anymore 😆

**Comment by mnonnenmacher** [comment]
> > In an upcoming change the `model` module will be renamed to `core`.
> 
> Did we really want to rename, or split? I don't recall anymore laughing

Actually both, but I didn't want to go into detail with the split because we still need to decide how exactly we want to do it.

**Comment by sschuberth** [comment]
Sorry, my recent merge caused a conflict here now.

**Review by sschuberth — APPROVED** [review]

**Comment by mnonnenmacher** [comment]
@sschuberth  Need another review because the GitHub actions did not start and I made a force push to trigger them again.

**Review by sschuberth — APPROVED** [review]

**Pull request merged**
