### PR TITLE
chore(docker): Revert "Upgrade Go to version 1.22.0"

### PR DESCRIPTION
**Pull request by fviernau**
Undo the major version upgrade as it break the fun tests for `GoDep`. The update should of course be done, but this requires investigating how it can work also for `GoDep`.

This reverts commit 550f922d23bbf8bd439a8ae1aafe61fa81dacd4b.

### CODE REVIEW

**Comment by heliocastro** [comment]
@fviernau I would say merge it the way it is now, as tonight the docker will cleanup with the nightly
My fault that the race condition PR isa not ready yet.

**Review by heliocastro — APPROVED** [review]
Looks good

**Comment by sschuberth** [comment]
> I would say merge it the way it is now

No, as this still [does not solve the underlying Go problem](https://github.com/oss-review-toolkit/ort/actions/runs/7991428880/job/21822552835?pr=8325#step:5:1283).

**Review by sschuberth — DISMISSED** [review]
I believe we can close this as it also does not solve the problem.

**Comment by fviernau** [comment]
> I believe we can close this as it also does not solve the problem.

Have the tests been executed on the previous or the current docker image - @sschuberth ?

**Comment by sschuberth** [comment]
> > I believe we can close this as it also does not solve the problem.
> 
> Have the tests been executed on the previous or the current docker image - @sschuberth ?

Ah, that I don't know. I'll dismiss my review.

**Comment by fviernau** [comment]
> I'll build the docker locally tomorrow and run the test to see if it works.

@sschuberth I've just build this docker locally and ran [1] successfully.
Can we merge?

[1] `./gradlew plugins:package-managers:go:funTest --tests GoDepFunTest`

**Review by sschuberth — APPROVED** [review]

**Pull request merged**
