### PR TITLE
Consistently spell it like "metadata" throughout the code base

### PR DESCRIPTION
**Pull request by sschuberth**
The "metadata" spelling seems to be way more common than "meta data" or
"meta-data".

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

### CODE REVIEW

**Comment by sschuberth** [comment]
Note that for yet more consistency this would require to also rename classes, functions and properties like `isMetaDataOnly`, but I'm not doing that here as it would break existing curations.

**Comment by mnonnenmacher** [comment]
> Note that for yet more consistency this would require to also rename classes, functions and properties like `isMetaDataOnly`, but I'm not doing that here as it would break existing curations.

You could use `@JsonAlias` to make it backward compatible.

**Comment by sschuberth** [comment]
> You could use `@JsonAlias` to make it backward compatible.

Right, but that would not work e.g. for rules using the `isMetaDataOnly` rule matcher. While I *really* like consistency, I'm not sure it's worth a breaking change here, and I also do not want to introduce a new `isMetadataOnly` rule matcher and deprecated the old one.

More opinions?

**Review by fviernau — DISMISSED** [review]

**Comment by fviernau** [comment]
> More opinions?

I'm fine with leaving `isMetaDataOnly` as-is.
I've found one more occurence of `meta-data` in `getting-started.md`. 
That could be fixed as well.

**Comment by sschuberth** [comment]
> I've found one more occurence of `meta-data` in `getting-started.md`.
> That could be fixed as well.

Done, I've found even some more occurrences in non-code places.

**Review by fviernau — APPROVED** [review]

**Comment by sschuberth** [comment]
Merging despite the unrelated failure.

**Pull request merged**
