### PR TITLE
ClearlyDefined improvements

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

### CODE REVIEW

**Comment by sschuberth** [comment]
@oheger-bosch can you help me adjusting the test for the last commit?

**Comment by oheger-bosch** [comment]
I will have a look.

**Comment by oheger-bosch** [comment]
I have added a commit, which should fix the failing test for `ClearlyDefinedStorage`. There is, however, still room for improving the test, e.g. by modifying the response of the definitions endpoint and testing whether the correct provenance is extracted.

**Review by oheger-bosch — APPROVED** [review]
Changes look good to me.

As the ClearlyDefined storage implementation is not yet actually in production use, I assume, it is acceptable that the new functionality - to obtain a `Provenance` - is not tested.

**Pull request merged**
