### PR TITLE
Fix formatting of some test assets

### PR DESCRIPTION
**Pull request by mnonnenmacher**
Align the indentation with how Jackson would serialize those files.

### CODE REVIEW

**Comment by sschuberth** [comment]
This is not only about indentation, but also about ordering. Is this due to the recent merge of https://github.com/oss-review-toolkit/ort/pull/4050?

**Comment by mnonnenmacher** [comment]
> This is not only about indentation, but also about ordering. Is this due to the recent merge of #4050?

I used IntelliJ to reformat the files, I don't think any order has changed.

**Comment by mnonnenmacher** [comment]
> > This is not only about indentation, but also about ordering. Is this due to the recent merge of #4050?
> 
> I used IntelliJ to reformat the files, I don't think any order has changed.

Looking at the diff, it seems that Git is really bad at doing diffs if only indentation is changed, maybe that gave the impression that the order has changed.

**Comment by sschuberth** [comment]
> Looking at the diff, it seems that Git is really bad at doing diffs if only indentation is changed, maybe that gave the impression that the order has changed.

It's also GitHub (not Git) being bad at this, but you're right, I verified locally with a more sophisticated diff tool that only indentation changed.

**Review by sschuberth — APPROVED** [review]

**Pull request merged**
