### PR TITLE
Stop polluting `Any` object with a `logger` property

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

### CODE REVIEW

**Comment by nnobelis** [comment]
As a sidenote, theses changes will most likely break any existing ORT plugins.

**Comment by sschuberth** [comment]
> As a sidenote, theses changes will most likely break any existing ORT plugins.

I guess they / most of them would still compile (as the `logger` of the base class would implicitly be used), but plugins would need to be adjusted (have `companion object : Logging` added) to list the correct class name in the output.

**Comment by nnobelis** [comment]
> > As a sidenote, theses changes will most likely break any existing ORT plugins.
> 
> I guess they / most of them would still compile (as the `logger` of the base class would implicitly be used), but plugins would need to be adjusted (have `companion object : Logging` added) to list the correct class name in the output.

True, but I was referring to the package renaming.

**Comment by sschuberth** [comment]
> True, but I was referring to the package renaming.

Hmm, if I'm not mistaken the only package renaming happened in the `helper-cli` module, which should not used programmatically anyway.

**Review by mnonnenmacher — APPROVED** [review]

**Pull request merged**
