### PR TITLE
Detekt: Enable AbsentOrWrongFileLicense

### PR DESCRIPTION
**Pull request by mnonnenmacher**
Enable the `AbsentOrWrongFileLicense` [1] rule to verify that the
correct license header is used in all Kotlin files.

[1] https://detekt.github.io/detekt/comments.html#absentorwrongfilelicense

### CODE REVIEW

**Comment by sschuberth** [comment]
I'm we should *either* keep / extend `detekt-rules/src/main/kotlin/OrtCopyrightHeader.kt` *or* enable this rule, but not have both. IIRC, back when I first looked at the `AbsentOrWrongFileLicense` rule it had some limitation, which is why I came up with our custom `OrtCopyrightHeader` rule. But might that the built-in `AbsentOrWrongFileLicense` rule works for us now.

**Comment by mnonnenmacher** [comment]
> I'm we should _either_ keep / extend `detekt-rules/src/main/kotlin/OrtCopyrightHeader.kt` _or_ enable this rule, but not have both. IIRC, back when I first looked at the `AbsentOrWrongFileLicense` rule it had some limitation, which is why I came up with our custom `OrtCopyrightHeader` rule. But might that the built-in `AbsentOrWrongFileLicense` rule works for us now.

I wasn't even aware of the custom rule. Regular expressions are only supported since the latest release 1.16.0, maybe that was the issue. I would then add another commit to remove the custom rule because it verifies only that there is a copyright statement in line 2, but not the rest of the header.

**Comment by sschuberth** [comment]
> Regular expressions are only supported since the latest release 1.16.0, maybe that was the issue.

Yes, probably.

**Review by sschuberth — APPROVED** [review]

**Comment by mnonnenmacher** [comment]
Merged, test failures were unrelated to detekt.

**Pull request merged**
