### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

### CODE REVIEW

**Review by mnonnenmacher — APPROVED** [review]
I have restarted the AppVeyor build as it looked like the errors were unrelated to your change.

**Comment by sschuberth** [comment]
> I have restarted the AppVeyor build as it looked like the errors were unrelated to your change.

I have seen this error in AppVeyor several times in the past days, which is why I today cleared the AppVeyor build cache. So maybe your retriggering would work now, but AppVeyor is not a required check anymore anyway.

**Comment by mnonnenmacher** [comment]
> ..., but AppVeyor is not a required check anymore anyway.

I forgot about that, shall we disable it?

**Comment by sschuberth** [comment]
> I forgot about that, shall we disable it?

I have a slight preference for keeping it around for a bit longer to double-check eventual Windows build failures on Azure. And I still like the way test results are displayed there the best.

*Edit:* But I just saw that AppVeyor failed again, despite the cleared cache. If we cannot get it to work anymore, there is no value in keeping it, and I'd be fine with removing the check.

**Pull request merged**
