### PR TITLE
Add a declared license mapping for http://json.codeplex.com/license

### PR DESCRIPTION
**Pull request by sschuberth**
The homepage lists being liensed under "MIT License" as a feature.

Also see the discussion at [1].

[1] https://github.com/oss-review-toolkit/ort/issues/3324#issuecomment-729163021

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

### CODE REVIEW

**Comment by sschuberth** [comment]
@mnonnenmacher or would adding this make our tests for https://github.com/oss-review-toolkit/ort/blob/8106e8e408eba6066db407e93a0f4ee8404eb6ea/analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output.yml#L59-L61 break?

**Review by fviernau — APPROVED** [review]

**Comment by mnonnenmacher** [comment]
> @mnonnenmacher or would adding this make our tests for
> 
> https://github.com/oss-review-toolkit/ort/blob/8106e8e408eba6066db407e93a0f4ee8404eb6ea/analyzer/src/funTest/assets/projects/synthetic/dotnet-expected-output.yml#L59-L61
> break?

Yes, you'll probably have to update those test assets as well.

**Comment by sschuberth** [comment]
> But there's no issue with doing that if that's what you mean, the declared license processing is tested separately.

Yes, that's what I meant. I wasn't sure whether you'd be fine with me breaking "your" example that you were referring to in the other issue. Done.

**Comment by oheger-bosch** [comment]
Typo in commit message: liensed -> licensed

**Review by fviernau — APPROVED** [review]

**Pull request merged**
