### PR TITLE
feat(docker): Replace Syft for Docker own Scout SBOM generator

### PR DESCRIPTION
**Pull request by heliocastro**
Docker now provides the way to generate embedded SBOM file through Docker Scout, and the engine underlying the process is same Syft previously used.

### CODE REVIEW

**Comment by sschuberth** [comment]
Should the files in `scripts/docker_snippets` be adjusted as well?

**Comment by heliocastro** [comment]
> Should the files in `scripts/docker_snippets` be adjusted as well?

Removed as well from there. I missed the custom_docker image .

**Comment by sschuberth** [comment]
Where do the generated SBOMs now end up to be? How / where are they embedded into the Docker images?

**Comment by heliocastro** [comment]
> Where do the generated SBOMs now end up to be? How / where are they embedded into the Docker images?

Here:
https://docs.docker.com/build/metadata/attestations/sbom/

Should we add this information on changelog ?

**Comment by sschuberth** [comment]
Well, what I believe we should do is to link to https://docs.docker.com/build/metadata/attestations/sbom/#sbom-generator via a `[1]` footnote from your existing sentence in the commit message, and then add another sentence saying something like "SBOMs are embedded into the created image and can be explored though "docker buildx imagetools inspect" and add another `[2]` footnote link to https://docs.docker.com/build/metadata/attestations/sbom/#inspecting-sboms after that sentence.

**Review by sschuberth — APPROVED** [review]

**Pull request merged**
