### PR TITLE
Fix AOSD2 export

### PR DESCRIPTION
**Pull request by GothHans**
When trying to upload the AOSD 2.0 file generated with ORT to the AOSD platform we encountered some problems.

After always creating a default "part", including empty fields (that where marked as optional but seem to be necessary) and removing hash algorithms other than SHA256 the file can now be uploaded to the Audi AOSD platform.

### CODE REVIEW

**Comment by GothHans** [comment]
@sschuberth  Currently the change to 2.1 is still ongoing. For new projects they suggest to use 2.1, but there is a converter that can convert files form 2.0 to 2.1 format (files can be converted on request, but the converter is not availabe for external use yet).

The structure of the 2.1 is significantly different from the 2.0 format. (They claim that 2.1 is the less complex format.)
We found it easyer to get the 2.0 to work, based on your previous implementation.
If you want to have a look into the 2.1 format, I could test if it works.

**Comment by sschuberth** [comment]
> The structure of the 2.1 is significantly different from the 2.0 format.

True, that's what I've figured from looking at the 2.1 schema.

> If you want to have a look into the 2.1 format, I could test if it works.

Let's first try to get 2.0 fully working, and add 2.1 support once it's finalized.

@GothHans there are a few issues with your PR that cause CI checks to fail. However, it's probably easier if I simply do these changes for you as you've luckily "Allow edits from maintainers" enabled.

**Review by sschuberth — APPROVED** [review]

**Comment by sschuberth** [comment]
Merging despite the unrelated `VulnerableCodeFunTest` failure.

**Comment by sschuberth** [comment]
Thanks for you contribution @GothHans!

**Pull request merged**
