### PR TITLE
ExperimentalScanner: Explain why a superfluous `suspend` modifier is kept

### PR DESCRIPTION
**Pull request by sschuberth**
Signed-off-by: Sebastian Schuberth <sschuberth@gmail.com>

### CODE REVIEW

**Review by mnonnenmacher — COMMENTED** [review]
I have that modifier there deliberately, because the function will start using coroutines, and so callers already have to be implemented accordingly.

**Comment by sschuberth** [comment]
> I have that modifier there deliberately, because the function will start using coroutines, and so callers already have to be implemented accordingly.

Ok, should I then suppress this inspection hint instead for now?

**Comment by sschuberth** [comment]
> Ok, should I then suppress this inspection hint instead for now?

Done that.

**Comment by mnonnenmacher** [comment]
> > Ok, should I then suppress this inspection hint instead for now?
> 
> Done that.

I have just created #5667 which I wanted to do for a long time, this would make the comment obsolete. I just need to do some testing.

**Pull request closed without merging**
