### PR TITLE
ReporterCommand: Write to a buffer before writing to the output file

### PR DESCRIPTION
**Pull request by sschuberth**
This allows us to get rid of the code to delete empty output files in
case of an exception.

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

### CODE REVIEW

**Comment by sschuberth** [comment]
@mnonnenmacher @fviernau I'm not sure why we didn't do to like this before. Did we maybe really run into memory issues?

**Comment by mnonnenmacher** [comment]
> @mnonnenmacher @fviernau I'm not sure why we didn't do to like this before. Did we maybe really run into memory issues?

Yes, that was the issue with large projects. If you want to get rid of handling the report files in the command class I think the better approach would be to pass the output dir to the reporters and let them take care of creating the file.

**Comment by sschuberth** [comment]
> pass the output dir to the reporters and let them take care of creating the file.

That's indeed better as that would also allow a reporter to create multiple files, which is a feature that I'll probably need soon.

**Comment by sschuberth** [comment]
> 
> 
> > pass the output dir to the reporters and let them take care of creating the file.
> 
> That's indeed better as that would also allow a reporter to create multiple files, which is a feature that I'll probably need soon.

See https://github.com/oss-review-toolkit/ort/pull/2735.

**Pull request closed without merging**
