### PR TITLE
Migrate from kotlintest to its successor kotest

### PR DESCRIPTION
**Pull request by sschuberth**
See https://github.com/kotest/kotest. The order of imports will be
adjusted later.

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

### CODE REVIEW

**Comment by sschuberth** [comment]
@mnonnenmacher @fviernau can you reproduce [this test failure](https://travis-ci.com/github/oss-review-toolkit/ort/builds/157725966#L1329)? As I cannot, locally.

**Comment by mnonnenmacher** [comment]
> @mnonnenmacher @fviernau can you reproduce [this test failure](https://travis-ci.com/github/oss-review-toolkit/ort/builds/157725966#L1329)? As I cannot, locally.
> 
> **Edit:** Besides the fact that this test should not be executed at all as part of a PR, as it's marked as `ExpensiveTag`, hmm...

Yes, it's also the reason why the cron build for master currently fails, so it's unrelated to your change:
https://travis-ci.com/github/oss-review-toolkit/ort/builds/157826777#L3464

So the question here is why the expensive tests are executed, the `GradleIntegrationTest` needs to be fixed separately.

**Comment by sschuberth** [comment]
> Yes, it's also the reason why the cron build for master currently fails

Your "yes" means you *can* reproduce it? Odd, because I still cannot, neither under Linux nor under Windows. Will you be able to provide a fix then?

**Comment by sschuberth** [comment]
> > So the question here is why the expensive tests are executed
> 
> Turns out you need to specify the fully qualified tag names now.

And that turns out to have been a [bug](https://github.com/kotest/kotest/issues/1346#issuecomment-608242597). I'll either create a follow-up to this PR if already approved, or change this PR to use version 4.0.2 once released, whatever comes first.

**Comment by sschuberth** [comment]
> I'll either create a follow-up to this PR if already approved

See https://github.com/oss-review-toolkit/ort/pull/2462.

**Pull request merged**
