### PR TITLE
spdx-utils: Turn some jackson deps into API dependencies

### PR DESCRIPTION
**Pull request by fviernau**
For consistency.

Signed-off-by: Frank Viernau <frank.viernau@here.com>

### CODE REVIEW

**Comment by sschuberth** [comment]
> For consistency.

What kind of consistency? To what?

I had given this topics some careful though in the past, and I believe the currently configuration to be correct. Also see [this related discussion](https://discuss.gradle.org/t/guidance-on-api-vs-implemetation-dependency-on-jackson-libraries/36056/1) that I started in the Gradle forum. In general, we [should](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation) use `implementation` dependencies if we can, and `api` dependencies only if we have to.

**Comment by fviernau** [comment]
> What kind of consistency? To what?

To: `model/build.gradle.kts` and to `utils/build.gradle.kts`.

**Comment by sschuberth** [comment]
> So, @sschuberth can you tell if we have to use `api` in above build files, but not in the `spdx-utils` one?

Yes, I believe that's how it is. If you search for all Jackson imports in the `spdx-utils` module then you'll see that all usages are either in

- function implementations
- internal properties
- class annotation which only affect internal code generation

Thus, in *this* module Jackson should stay an `implementation` dependency IMO. And in general, you have to decide this on a case-by-case basis, and cannot make such a change globally "for consistency".

**Comment by fviernau** [comment]
Thanks @sschuberth, closing the PR then.

**Pull request closed without merging**
