### PR TITLE
Update config-file-resolutions-yml.md - add flag to example

### PR DESCRIPTION
**Pull request by VaeterchenFrost**
Add the described flag in the example call.

### CODE REVIEW

**Comment by sschuberth** [comment]
Thanks for the contribution! Some commit message nits, please

- use imperative mood: "Added described flag in example call." -> "Add the described flag in the example call."
- sign-off your commit (`git commit -s`)

**Comment by VaeterchenFrost** [comment]
Oh, sure. I used GitHub Desktop for this commit, which eventually "*does not support commit signing*".

**Comment by VaeterchenFrost** [comment]
Eventually GitHub signed with a verified signature using GitHub’s key after that...

**Comment by sschuberth** [comment]
> Oh, sure. I used GitHub Desktop for this commit, which eventually "_does not support commit signing_".

That fine, as there is a difference between "signing a commit" (`git commit -S`, upper case) and "sign-off a commit" (`git commit -s`). We only ask for the latter to acknoledge the DCO (also see the details next to the respective check).

**Comment by VaeterchenFrost** [comment]
Thank you for the help, now it should be included and updated.

**Review by sschuberth — APPROVED** [review]

**Pull request merged**
