### PR TITLE
ResolvedLicense: fix toResolvedCopyrights to identify the same copyri…

### PR DESCRIPTION
**Pull request by bennati**
…ght in multiple files.

Fix a regression when a copyright is present in multiple files in the same repository.
The expected behavior is that the all findings of the copyright are returned, if they have different paths.
The previous behavior was that only the last finding was kept, as 'statementToFinding' is built using 'associateBy' which "If any two elements would have the same key returned by keySelector the last one gets added to the map."

Signed-off-by: Stefano Bennati <stefano.bennati@here.com>

Please ensure that your pull request adheres to our [contribution guidelines](https://github.com/oss-review-toolkit/.github/blob/main/CONTRIBUTING.md). Thank you!

### CODE REVIEW

**Comment by bennati** [comment]
We identified this regression in one of our scans where `resolvedLicense.getResolvedCopyrights()` returned 
```
[[[ResolvedCopyrightFinding(statement=Copyright (c) 2021-2022 HERE Global B.V. and its affiliate(s), location=TextLocation(path=src/index.html, startLine=4, endLine=4), matchingPathExcludes=[])]]]
```
instead of
```
[[[ResolvedCopyrightFinding(statement=Copyright (c) 2021-2022 HERE Global B.V. and its affiliate(s), location=TextLocation(path=LICENSE, startLine=1, endLine=1), matchingPathExcludes=[]), 
ResolvedCopyrightFinding(statement=Copyright (c) 2021-2022 HERE Global B.V. and its affiliate(s), location=TextLocation(path=src/assets/LICENSE, startLine=1, endLine=1), matchingPathExcludes=[]), 
ResolvedCopyrightFinding(statement=Copyright (c) 2021-2022 HERE Global B.V. and its affiliate(s), location=TextLocation(path=src/index.html, startLine=4, endLine=4), matchingPathExcludes=[])]]]
```

**Comment by sschuberth** [comment]
Let me come up with a test for this first...

**Comment by sschuberth** [comment]
> Let me come up with a test for this first...

@bennati and @zhernovs, I'm having trouble reproducing your issue. Do you agree that the test add in https://github.com/oss-review-toolkit/ort/pull/6109/commits/dea34c2db58ccb9b2a1cfa0db442ff0e75d1e473 should reveal is there was any issue?

Also, which version of ORT are you using? Can it be that you're using a version that lacks https://github.com/oss-review-toolkit/ort/pull/6016?

**Comment by zhernovs** [comment]
In our case the issue were caused on a project that has the same license (same statement and years) in root of the project and in subdirectories (src, src/assets). So perhaps you can't reproduce the issue because there are different years in https://github.com/oss-review-toolkit/ort/commit/dea34c2db58ccb9b2a1cfa0db442ff0e75d1e473? 

We facing this issue on every version newer than https://github.com/oss-review-toolkit/ort/commit/3e9d11d83626c7886f2706d72ce05dddd40937cc including https://github.com/oss-review-toolkit/ort/commit/03bea2277177284e2a504b1a90f7b8c90a2f8622

Please @bennati correct me if I'm wrong.

**Comment by bennati** [comment]
Correct, we applied the fix https://github.com/oss-review-toolkit/ort/pull/6016 (which this fix reverts because the values in `statementToFinding` are now processed statements).
Try setting the year of both copyrights to be the same.

**Comment by sschuberth** [comment]
> Try setting the year of both copyrights to be the same.

Thanks, that way I can reproduce the issue. I've added a test and am proposing a more minimal fix in https://github.com/oss-review-toolkit/ort/pull/6113. Would you mind testing it?

**Comment by bennati** [comment]
Thanks @sschuberth, the test was successful!

**Comment by sschuberth** [comment]
> Thanks @sschuberth , the test was successful!

Great, then let me close this in favor of the other PR. Many thanks for the report and initiative to fix it!

**Pull request closed without merging**
