### PR TITLE
Improve readability

### PR DESCRIPTION
**Pull request by pietbrauer**
I stumbled across some typos and structured the Q&A to be able to differentiate between questions and answers.

### CODE REVIEW

**Comment by sschuberth** [comment]
Hey @pietbrauer, thanks for the contribution, but what's the reason to close this unmerged?

**Comment by pietbrauer** [comment]
I was too eager to click on the open PR and didn't read the contribution guidelines.

**Comment by sschuberth** [comment]
I see. But you simply could have amended your commit with a signoff and force-pushed to our branch instead of [opening a new PR](https://github.com/oss-review-toolkit/ort/pull/2770) 😉

**Comment by pietbrauer** [comment]
That was my initial plan but the reopen button was greyed out after the force push…

**Comment by sschuberth** [comment]
Ah, good to know, so apparently the order matters. Next time just reopen first, and then force-push 😀

**Pull request closed without merging**
