### PR TITLE
fix(node): Support deserializing `PackageJson.author` from an array

### PR DESCRIPTION
**Pull request by fviernau**
Fixes: #9201.

### CODE REVIEW

**Comment by sschuberth** [comment]
@fviernau I assume you overlooked that I had assigned https://github.com/oss-review-toolkit/ort/issues/9201 to myself? I had a (different) solution almost ready, but then needed to take a break to do something else.

**Comment by fviernau** [comment]
> @fviernau I assume you overlooked that I had assigned #9201 to myself? I had a (different) solution almost ready, but then needed to take a break to do something else.

Yes, indeed. When I looked at the issue it was still unassigned, maybe I missed to hit the refresh button.

**Comment by sschuberth** [comment]
> I just saw you assigned at 2:34pm and I filed the PR at 2:36pm. I took me more than 2 minutes of course to craft the fix.

But before that, I already wrote over [here](https://github.com/oss-review-toolkit/ort/issues/9201#issuecomment-2376669153) that "I can give it a try" (yesm it was an edit to the post, but directly after I wrote the original post).

> Can we go ahead with this one now anyway?

I'd rather not, because I believe the change goes into the wrong direction: In order to also solve your `TODO: The string from the JSON primitive could be parsed into the dedicated author properties.`, I believe the deserializer should continue to normalize on the most detailed objection notation, rather than on the array notation.

**Comment by fviernau** [comment]
> But before that, I already wrote over [here](https://github.com/oss-review-toolkit/ort/issues/9201#issuecomment-2376669153) that "I can give it a try" (yes, it was an edit to the post, but directly after I wrote the original post).

I don't see a point in discussing this further.

> I'd rather not, because I believe the change goes into the wrong direction: 

I don't think that it changes direction at all. 

> In order to also solve your `TODO: The string from the JSON primitive could be parsed into the dedicated author properties.`, 

This is something additional, and it easily fits on top of my PR without the need to refactor. 

> I believe the deserializer should continue to normalize on the most detailed objection notation, rather than on the array notation.

I believe there is a misunderstanding. With may PR, it continued to handle the most detailed object notation. It even handles the case if JsonObjects were in that array.

**Comment by fviernau** [comment]
@sschuberth can we move on with this please, I'd love to have this bug fixed and not keep this around being blocked for unclear reason.

**Comment by sschuberth** [comment]
> @sschuberth can we move on with this please, I'd love to have this bug fixed and not keep this around being blocked for unclear reason.

I don't currently have time to continue working on my alternate proposal. So let's merge your PR to have a fix for the upcoming release. If required to make things easier for me, I could still revert it locally.

**Review by sschuberth — APPROVED** [review]

**Pull request merged**
